### ISSUE TITLE
Copying text from link diff includes line numbers

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#10015]
# Issue Description
Say the text showed in a diff (*.changes file) looks like this: 

```
@@ -1,83 +1,4 @@
 -------------------------------------------------------------------
Sun Aug  2 07:13:17 UTC 2020 - ....

- Update to 5.73.0
  * New feature release
  * For more details please see:
```
Selecting the text and copy/pasting results into 

```
 1@@ -1,83 +1,4 @@
 2 -------------------------------------------------------------------
 3-Sun Aug  2 07:13:17 UTC 2020 - ...
 4-
 5-- Update to 5.73.0
 6-  * New feature release
 7-  * For more details please see:
```
Expected Result
============
The line numbers followed by the '-' should not be included in the copied text

How to Reproduce
============
1. Click on a "link diff"
2. Select text shown in the diff
3. copy and paste that text

**Comment by dmarcoux** [comment]
_Note for developers:_ We rely on [CodeRay](https://github.com/rubychan/coderay) for the diffs and it seems to be possible to prevent selection of line numbers by using `line_numbers: :table` instead of `line_numbers: :inline`. I gave it a try and it somehow rendered the line numbers, then the diffs' content.

![line_numbers_table](https://user-images.githubusercontent.com/1102934/90374423-c76ea700-e073-11ea-9425-8f12d4475bef.png)

**Comment by vpereira** [comment]
To copy without the line number you have to click on "View File" and there you can copy without the line numbers.. Does it work for you @rhabacker ?

**Comment by rhabacker** [comment]
the former link is gone, but the "View file" link at https://build.opensuse.org/package/rdiff/windows:mingw:win32/mingw32-filesystem?linkrev=base&rev=133 does not work.

**Comment by rhabacker** [comment]
With the changes mentioned in the section **Enhancing Code Changes**` at https://openbuildservice.org/2023/01/25/request-workflow-redesign/ this issues has been fixed.
