### ISSUE TITLE
Places bar steals valuable real estate

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#10017]
Change introduced with https://github.com/openSUSE/open-build-service/pull/10007

The 'places' used the shown only when explicitly asking for it. After the above mentioned change, it is now constant on screen (whereas the links are not used every 2 minutes) and pushing the real content to the side

From my personal experience, I did use the places overlay bar, byt by far not sufficiently enough to worry it being behind one additional click to show it.

**Comment by jengelh** [comment]
Not a lot of space left for the center part; like 96 columns for the .spec file.
![ff](https://user-images.githubusercontent.com/8861948/90392249-cd25b600-e08e-11ea-8153-3ef0810fae37.png)

**Comment by badshah400** [comment]
Just came here to report this and suggest that if we must have a sidebar, perhaps doing something like what bitbucket does may be helpful. GH doesn't allow me to upload screen captures, but you can see here <https://bitbucket.org/njet/njet/downloads/>, for instance. Personally, I also had no problems with the previous overlay sidebar.

**Comment by vpereira** [comment]
We have some background about it on our Blog: https://openbuildservice.org/2020/08/17/left-side-navigation/

**Comment by badshah400** [comment]
Thanks, that does throw some light on why the sidebar was conceived. In my opinion, the implementation can be better. Also, the current sidebar leads to the actual work area getting cut off horizontally (1920x1080 display). See, e.g. <https://build.opensuse.org/request/show/815792> (screenshot attached). If that is worth a new issue, please let me know.

![Screenshot from 2020-08-17 15-26-40](https://user-images.githubusercontent.com/3532467/90401338-1c271780-e09e-11ea-8257-d3e40f4a09ea.png)

**Comment by saraycp** [comment]
Thank you all for your feedback. :bouquet:

As mentioned in the blog post, we also got a considerable amount of feedback against the previous menu structure. After exhaustive research, we concluded this new version brings many benefits and follows a dashboard pattern, which is widespread.

Now it seems it doesn't bring a big benefit for you, especially in the request page. But this page needs to be revisited and, in fact, the actions haven't been moved to the left menu yet. So you'll probably see the advantages in the near future.

Anyway, please don't forget that the new structure applies only to the beta program. That means the feature is under review and we will take the incoming feedback into account to make it even better if possible.

**Comment by aaronpuchert** [comment]
> The 'places' used the shown only when explicitly asking for it. After the above mentioned change, it is now constant on screen (whereas the links are not used every 2 minutes) and pushing the real content to the side

This shows both places and actions. I think what you want depends somewhat on how you use OBS, but the sidebar is only shown for larger resolutions where the space should be available.

> Not a lot of space left for the center part; like 96 columns for the .spec file.

On the other hand, there is still whitespace in your screenshot, and lines substantially longer than 100 chars are not very nice.

The recommendation by typographers to have lines between 80–90 characters long does not directly apply to code, but very long lines are more of a waste than the menu in my opinion.

> Thanks, that does throw some light on why the sidebar was conceived. In my opinion, the implementation can be better. Also, the current sidebar leads to the actual work area getting cut off horizontally (1920x1080 display). See, e.g. https://build.opensuse.org/request/show/815792 (screenshot attached). If that is worth a new issue, please let me know.

I noticed that as well. I think the issue here is that the work area isn't made to fit the screen, so there is horizontal scrolling. Making the diff take up whatever horizontal space it needs is not the right solution IMO, instead it should be cut off. The individual files have horizontal scrolling anyway. Some people also like wrapping, but others are vehemently opposed, so not sure about that.

**Comment by dmarcoux** [comment]
> (...) I think the issue here is that the work area isn't made to fit the screen, so there is horizontal scrolling. Making the diff take up whatever horizontal space it needs is not the right solution IMO, instead it should be cut off. The individual files have horizontal scrolling anyway. Some people also like wrapping, but others are vehemently opposed, so not sure about that.

Thank you @aaronpuchert for your comment. Having the content take whatever horizontal space it needs is a bug. It's not intentional. I'm looking into what is causing this and will be addressing this as soon as possible.

**Comment by guoyunhe** [comment]
One more thing: the left sidebar isn't scroll-able when the list is too long...

![图片](https://user-images.githubusercontent.com/5836790/90556631-e703ed80-e1a1-11ea-8cdd-e89b8eb66223.png)

I really just want something similar to GitHub/GitLab. Make use of navbar, not sidebar.

**Comment by jengelh** [comment]
Ironically, I already asked for a space-efficient navbar in #9304.

**Comment by aaronpuchert** [comment]
> I really just want something similar to GitHub/GitLab. Make use of navbar, not sidebar.

Now I'm confused, doesn't [GitLab have a sidebar](https://invent.kde.org/plasma/kwin)? To be fair, it's scrollable and can be collapsed to symbols only, but it's literally called "sidebar" there.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make left navigation collapsible](https://trello.com/c/eebshmgH/2008-make-left-navigation-collapsible)

**Comment by guoyunhe** [comment]
I don't think "making it collapsible" solve the issue. The design of sidebar missed the point.

Let's take GitLab as good example (KDE Invent instance):

![图片](https://user-images.githubusercontent.com/5836790/96102351-1e132880-0edf-11eb-9f5e-ee783f95bcaf.png)

The top navbar is for global navigation, to show global navigation and search. It uses less space because these navigation links are not that important.

The left sidebar is for project navigation, to allow you quickly navigate from all features of the project/package. It is used for more important content so it can use more space.

And more importantly, GitLab doesn't have other type of sidebars in the main area. But OBS has a lot of them:


![图片](https://user-images.githubusercontent.com/5836790/96104209-397f3300-0ee1-11eb-9f4b-3d74f3b0433b.png)

![图片](https://user-images.githubusercontent.com/5836790/96104290-5287e400-0ee1-11eb-84b5-a8bd3fa65b39.png)

![图片](https://user-images.githubusercontent.com/5836790/96104697-d3df7680-0ee1-11eb-9265-e74268485c29.png)

In result, many texts are break into two lines on small screens when the sidebar is open.

That is why I think GitHub like (no-sidebar) design fits OBS better.

Do we really need such an empty navbar? We have plenty of space on the left. You can put all places links there. Just like GitHub and GitLab does.

Why not just apply a similar design that has been proven to be successful?

**Comment by eduardoj** [comment]
@guoyunhe 

> In result, many texts are break into two lines on small screens when the sidebar is open.

What about closing the sidebar? The issue is marked as fixed with the merge of the pull request, but that changes are not yet deployed. Anyway, you could also try the changes locally [setting up a development environment](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md#how-to-setup-an-obs-development-environment).
