### ISSUE TITLE
Arch Community cannot be activated

### ISSUE THREAD

**Issue by sxmarquardt** [openSUSE/open-build-service#10352]
# Issue Description

Please excuse if this is the wrong address for this issue - I am pretty new to OBS; still learning.
The "Arch Community" button in https://build.opensuse.org/project/add_repository_from_default_list/home:...
does not work. It is there but cannot be selected.

Expected Result
============
Clicking the Arch Community tick should enable the Arch Community distro

How to Reproduce
===============
1. Go to 'https://build.opensuse.org/project/add_repository_from_default_list/home:[ID]'
2. Click on 'Arch distributions - Arch Community'

Further Information
===============
I require hdf5 and netcdf for a project both of which seem to exist only in Community but not in Extra.
In case anyone has a hotfix to solve these dependencies in Arch Extra instead, I highly appreciate help.

**Comment by hennevogel** [comment]
This should work now.

The Arch Community `Distribution`s had the same `reponame`. We need to add a uniqness validation to this.

**Comment by adrianschroeter** [comment]
On Mittwoch, 28. Oktober 2020, 17:25:01 CET Henne Vogelsang wrote:
> This should work now.
> 
> The Arch Community `Distribution`s had the same `reponame`. We need to add a uniqness validation to this. 

no, it should be possible to have multiple choices for same repo

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
On Mittwoch, 28. Oktober 2020, 17:30:46 CET Adrian Schröter wrote:
> On Mittwoch, 28. Oktober 2020, 17:25:01 CET Henne Vogelsang wrote:
> > This should work now.
> > 
> > The Arch Community `Distribution`s had the same `reponame`. We need to add a uniqness validation to this. 
> 
> no, it should be possible to have multiple choices for same repo

and esp. here it was on purpose, since it makes no sense to build for both obviously

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hennevogel** [comment]
I don't get it. If you have multiple choices and you choose both, which one do you build for?

**Comment by sxmarquardt** [comment]
Hi @both and thanks for the quick reply! I tried now, however it still seems impossible to activate the Arch Community (Extra is missing some packages, in my case netcdf, so I wouldn't build for Extra anyhow). The tick box is there, but activating it only activates the other (Extra).

**Comment by adrianschroeter** [comment]
On Mittwoch, 28. Oktober 2020, 17:35:37 CET Henne Vogelsang wrote:
> I don't get it. If you have multiple choices and you choose both, which one do you build for?

it makes sense only to build for one of them. It could shown via radio box selection instead of 
check boxes.

The rational behind is that one repo contains additional packages to the other one like in
the Arch case. So, when you are able to build for the Core it will also work when the
user has added the additional Community and/or Extra repos.

On the other hand developers may need the additional content from community and/or Extra 
repos in other cases, but that reduces the trust level and may make it also impossible
to install it on installations which avoid the additional repos on purpose.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by adrianschroeter** [comment]
On Donnerstag, 29. Oktober 2020, 08:10:46 CET sxmarquardt wrote:
> Hi @both and thanks for the quick reply! I tried now, however it still seems impossible to activate the Arch Community (Extra is missing some packages, in my case netcdf, so I wouldn't build for Extra anyhow). The tick box is there, but activating it only activates the other (Extra).

okay, but you know that you can manualy configure it via the project meta, right?

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by sxmarquardt** [comment]
That's certainly an alternative, yes. Thanks. Will have to figure out how, though. In case you are aware of any example or tutorial I'd appreciate any hint.

**Comment by hennevogel** [comment]
@sxmarquardt there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members.

**Comment by hennevogel** [comment]
I created a feature for the missing functionality #10356 

Thanks for reporting @sxmarquardt

**Comment by sxmarquardt** [comment]
Hi Henne, thanks for your help! Will follow the feature request you created and crawl through the mailing list to eventually seek some help with my more specific problem.

Thanks again for your quick response, @adrianschroeter and @hennevogel !
