### ISSUE TITLE
Additional prjmeta rebuild mode

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#10372]
**Is your feature request related to a problem? Please describe.**
When the openSUSE:Factory prjconf is changed with regards to `Prefer` lines et al, no package rebuilds happen.
I think this is a result of `<repository name="standard" rebuild="local">` in the prjmeta.

**Describe the solution you'd like**
An extension of the available rebuild modes, for example `local+prjconf` that would slot in logically between `direct` and `local`.

**Describe alternatives you've considered**
rebuild=direct. Does not sound like Factory wants it.

cc @DimStar77

**Comment by adrianschroeter** [comment]
prjconf never is triggering anything. Only when this leads to dependency changes and you are in a clean mode.

we could implement a factory specific mode, but it would need to be defined how this should look alike.

I am closing this, since prjconf changes alone will never trigger rebuilds for good reason.
