### ISSUE TITLE
Text for Empty List of a User's Involved Projects/Packages Is Sometimes Wrong

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#10811]
# Issue Description
On the profile page of a user, the text for an empty list of involved projects/packages is sometimes wrong. For example, if a user is only involved in projects and we filter by _Packages_, a text is displayed to let the current user that there are no involved projects/packages. This is wrong since the user is involved in some projects.

Expected Result
============
We should take into consideration whether the user is involved in projects/packages when filtering by _Packages_ or _Projects_ and change the text if needed.

How to Reproduce
===============

It's quite easy to reproduce in our development environment. Create some test data by running `bundle exec rake dev:development_testdata:create` in the frontend container.

1. Go to http://localhost:3000/users/Iggy and see that Iggy is involved in the project `home:Iggy`
2. Filter by _Packages_
3. See the wrong text `

Further Information
===============

Iggy's profile and the list of involved projects/packages:
![iggy](https://user-images.githubusercontent.com/1102934/109150225-dd6acc00-7768-11eb-9766-26cd73e30b65.png)

Filter by _Packages_ of Iggy's involved projects/packages (with the wrong text):
![wrong-text](https://user-images.githubusercontent.com/1102934/109150227-de036280-7768-11eb-8b62-29737517a06b.png)

**Comment by logological** [comment]
The problem occurs not just for the Projects/Packages drop-down but also the Role drop-down and the free-text filter.  For example, if I type in the free-text filter the name of some package I'm not involved in, I still get the "This user is not involved in any project or package." message.  This message is misleading because it's not true that I'm not involved in _any_ project or package; it's just that I'm not involved in any project or package that matches the filters.
