### ISSUE TITLE
downloaded debian package don't match built package

### ISSUE THREAD

**Issue by sunderme** [openSUSE/open-build-service#1130]
http://download.opensuse.org/repositories/home:/jsundermeyer/xUbuntu_14.04/amd64/texstudio_2.10.0_amd64.deb
package seems to be from a previous revision of the source code, md5sum of the downloaded deb-file  does not match with the sums given in details !

**Comment by afaerber** [comment]
The packages shown in the Web UI (build.opensuse.org) may be newer than those published on download.opensuse.org - publishing only happens when *all* relevant packages in the project have finished building. It would only be a bug if checksum and package were inconsistent in the Web UI.

**Comment by sunderme** [comment]
Well the checksums did not match either.

Am 03.10.2015 um 14:38 schrieb Andreas Färber:

**Comment by hennevogel** [comment]
Please be a little bit more specific and tell us which packages and which checksums...

**Comment by sunderme** [comment]
I can't reproduce the issue anymore.
Though now I am avoiding it by letting OBS increase the build number
automatically.

best regards,
  Jan

Am 16.10.2015 um 16:46 schrieb Henne Vogelsang:

**Comment by zanchey** [comment]
We are also seeing this in [shells: fish:release:2/fish](https://build.opensuse.org/package/show?project=shells%3Afish%3Arelease%3A2&package=fish):

The [Packages metadata](http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/Packages) says:

```
Filename: ./amd64/fish_2.2.0-1_amd64.deb
Size: 1722530
MD5sum: adf0a00e11c4d6d55daf493c500892b2
SHA1: 5c7f1ba9a5411c125bb3f25444faa7c83396baa0
SHA256: b2cb74f255a8c53af53de8a8b2241c0f29d0d7715c035fa73221bbe62539d31e
```

but:

```wget http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/amd64/fish_2.2.0-1_amd64.deb; ls -l fish_2.2.0-1_amd64.deb; md5sum fish_2.2.0-1_amd64.deb; sha1sum fish_2.2.0-1_amd64.deb
-rw-r--r--  1 david  staff  1722112 19 Dec 23:14 fish_2.2.0-1_amd64.deb
MD5 (fish_2.2.0-1_amd64.deb) = 140e31df39226c87543102df8092c967
33d3a3919a0f9bb351b7e40b4329be221e65bee7  fish_2.2.0-1_amd64.deb
```

**Comment by zanchey** [comment]
Interestingly in our case the sizes from `osc ll -b` matches the repository metadata, not the downloaded files, eg:

```
Debian_7.0/i586
    16239 Feb 04 09:12 _buildenv
      792 Feb 04 09:12 _statistics
  6251688 Feb 04 09:12 fish-dbg_2.2.0-1_i386.deb
     4108 Feb 04 09:12 fish_2.2.0-1.debian.tar.xz
     1623 Feb 04 09:12 fish_2.2.0-1.dsc
     1824 Feb 04 09:12 fish_2.2.0-1_i386.changes
  1703730 Feb 04 09:12 fish_2.2.0-1_i386.deb
  2213037 Feb 04 09:12 fish_2.2.0.orig.tar.gz
```

Could it be that the files are not getting correctly synced after being built?

**Comment by zanchey** [comment]
Interestingly, the file that is being retrieved seems to vary with the user-agent of the client:

```
> curl -o - -L http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/./i386/fish_2.2.0-1_i386.deb | sha1sum
11425a07040b6fa60bc27e83c3e1c9fb5bf043eb -
> curl --user-agent "Debian APT-HTTP/1.3 (1.0.9.8.2)" -o - -L http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/./i386/fish_2.2.0-1_i386.deb | sha1sum
f201a586eb5fb058d3b732ac5bfa1a296ffbf648  
```

**Comment by mlschroe** [comment]
That's because the MirrorBrain config contains:
```
MirrorBrainExcludeUserAgent *APT-HTTP*
```
I.e. requests from apt will not be redirected.

**Comment by mlschroe** [comment]
(Because apt can't handle redirects...)

**Comment by zanchey** [comment]
So does that mean that MirrorBrain is looking at a different repository?

**Comment by mschnitzer** [comment]
Not sure which part of the application affects that so I attached the `appliance` label to it.

**Comment by micah** [comment]
There is something wrong with the repository for knot-resolver Debian_10. The [Packages file](http://download.opensuse.org/repositories/home:/CZ-NIC:/knot-resolver-latest/Debian_10/Packages) lists the size of the package knot-resolver_5.1.3-1_amd64.deb as `293328` bytes but if you [download the actual package](http://download.opensuse.org/repositories/home:/CZ-NIC:/knot-resolver-latest/Debian_10/amd64/knot-resolver_5.1.3-1_amd64.deb) you find that it is `293436` bytes in size. 


This breaks the ability to install the package with apt, because apt will refuse to install a package that does not cryptographically validate, in this case the size is different from the signed version of the file:

  File has unexpected size (293436 != 293328). Mirror sync in progress? [IP: 198.252.153.38 9999]
  Hashes of expected file:
   - SHA256:68d47a8488987a9da8a3ea89523f92a67415bc8c2f8f3ed2f66817f3f1697a2d
   - SHA1:d272ecc5c32c0e4c1256fa99a63c019a53df8eb9 [weak]
   - MD5Sum:001f79ad908b7b65df715b7cea1d24c0 [weak]
   - Filesize:293328 [weak]

If the hash of the file differs from the hash that is in the file that has been signed by the archive, that means that the file is different than it should be, and apt is doing the right thing by refusing to install something that is not cryptographically authenticated.

You cannot ship a file that has a different size than what is *cryptographically* assured to be a another size. The whole point of generating the hashes, and then signing the file, is to assure that you are getting the exact same file.

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from us.

However there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the OBS IRC chat (irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](mailto:opensuse-buildservice+subscribe@opensuse.org) ([archive](http://lists.opensuse.org/archive/opensuse-buildservice/)). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members. 

Thank you for your consideration.
