### ISSUE TITLE
Log files not public available any more for sharing with public upstream projects

### ISSUE THREAD

**Issue by skriesch** [openSUSE/open-build-service#11443]
# Issue Description
2 weeks ago, it was possible to share failed build logs with upstream projects anymore.
Example shared link:
https://build.opensuse.org/build/openSUSE:Factory:zSystems/standard/s390x/cross-epiphany-gcc11-bootstrap/_log

Users without any openSUSE account are receiving the following message:
 _anonymous_user(Anonymous user is not allowed here - please login):_

Are we an open-source community or not?

Expected Result
============
All build logs links should be sharable outside of openSUSE in Bugzilla or on Github.
All people without any openSUSE account should be able to have access.

How to Reproduce
===============
1. Login to OBS
2. Go to any failed package 
3. Open Logs
4. Copy link from browser
5. Logout
6. Open link again
7. Error:  _anonymous_user(Anonymous user is not allowed here - please login):_

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org
* Exact server version (in case a private instance is used)

**Comment by coolo** [comment]
What does being an open-source community have to do with requiring an account for certain actions?

But as a matter of fact, if you link  https://build.opensuse.org/package/live_build_log/openSUSE:Factory:zSystems/cross-epiphany-gcc11-bootstrap/standard/s390x to your forums, it will work. Because the "Download logfile" behaves different for logged in users than it does for non-logged in users. And I guess either you shared that link 2 weeks ago or you copied the link from browser while not being logged in yourself.

Because that behavior is in place since [2016](9e49c4110b0041fbd15b69626d5543c8d55d9d4e)

**Comment by skriesch** [comment]
Reading log information is no action. I and others want to share such information with upstream communities (and in my case IBM). Downloading log files and attaching them to Bugzilla or to Github issues is some wasteful work (for the bug tracking system and the bug reporter because of possible changes).

I thought I would have shared a link with _log at the end with an upstream project and they were able to analyze deeper with that. 

Is it possible to create a redirect from the private log link to the public log link?

**Comment by hennevogel** [comment]
Just share the public link instead please.
