### ISSUE TITLE
linux:version constraint not evaluated/ignored correctly

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#11967]
Got a private OBS instance which links openSUSE.org in the usual manner. The openSUSE:Leap:15.3 buildconfig contains `Constraint: linux:version:min 3.0.0`. My workers are chroot-based. The constraint is improperly evaluated to the point that no building is possible at all.

```
$ osc bl standard x86_64|o
package build was not possible:

no compliant workers (constraints mismatch hint: linux:version)

Please adapt your constraints.
```

**Comment by adrianschroeter** [comment]
constraints are more or less intentionally not supported on chroot, since there can not be a clean seperation of resources.

we could have support for this single particular example, but not sure if makes sense, since people will be confused which of the constraints are applied and which not.

therefore closing this one.
