### ISSUE TITLE
Deadlocks on groups table as the table is written to invalidate caches in memcached

### ISSUE THREAD

**Issue by darix** [openSUSE/open-build-service#12125]
We see a lot of deadlocks on the groups table which seems to be triggered by the cache invalidation in models/bs_request.rb and models/review.rb. We can mostly trigger it with requests where many actions  or users are involved. I saw single deadlocks where one DB query waited on 177 rows conflicting with others. We worked around it by adding an early return in bs_request.rb update_cache.

Cache invalidation by constantly writing to the DB seems counter productive.

I guess Adrian has one attempt to fix it in https://github.com/openSUSE/open-build-service/pull/12115

**Comment by hennevogel** [comment]
> Cache invalidation by constantly writing to the DB seems counter productive.

It's a rather normal practice to base the cache key on the `updated_at` column.  See the [rails caching guide](https://guides.rubyonrails.org/caching_with_rails.html#russian-doll-caching) and [cache_key](https://api.rubyonrails.org/classes/ActiveRecord/Integration.html#method-i-cache_key).

My guess is that the root cause of this deadlock is not the touching of User/Group but that monstrous request being [handled](https://github.com/openSUSE/open-build-service/blob/ca2ac70b6f5668c2248c373f991da73e93a9c8cb/src/api/app/controllers/request_controller.rb#L142) in one [gian transaction](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-transaction)

Depending on the amount and character of the `BsRequestActions` and in the `BsRequest` you will run into *many* kind of timeouts blocking each other.

Normally you would build something like this in memory, validate it and commit it in single writes.

**Comment by darix** [comment]
writing update_at to clear caches feels very ugly TBH.

**Comment by vpereira** [comment]
> writing update_at to clear caches feels very ugly TBH.

that's literally what is suggested in the [documentation](https://guides.rubyonrails.org/caching_with_rails.html) @darix ...There is even a method to just do that https://apidock.com/rails/v6.1.3.1/ActiveRecord/Persistence/touch
