### ISSUE TITLE
GitHub does not display OBS workflow results after a push event

### ISSUE THREAD

**Issue by ashaduri** [openSUSE/open-build-service#12218]
# Issue Description

I have OBS set up as a CI for my GitHub repository.

However, after a push event in my GitHub repository, OBS build results do not appear in GitHub's [Actions page](https://github.com/ashaduri/gsmartcontrol/actions).

The GitHub->OBS webhook works and returns HTTP 200. The packages in OBS are built correctly.

I cannot inspect the [Push Event](https://build.opensuse.org/my/tokens/5904/workflow_runs/20556) in OBS as it gives `500: Internal Server Error`.

- GitHub repository: [gsmartcontrol](https://github.com/ashaduri/gsmartcontrol).
- OBS repository: [home:alex_sh:gsmartcontrol:github_ci:main](https://build.opensuse.org/project/show/home:alex_sh:gsmartcontrol:github_ci:main).
- OBS workflow file: [workflows.yml](https://github.com/ashaduri/gsmartcontrol/blob/a5771f1af94b8eda69cb14ee18ba913631b99b6f/.obs/workflows.yml).

Expected Result
============
https://github.com/ashaduri/gsmartcontrol/actions, or at least some page on GitHub should show OBS workflow results (after a push event).

Further Information
===============
* OBS instance: build.opensuse.org

**Comment by dmarcoux** [comment]
Link to the [exception in Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/620d011084bf46054908875a).

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix issue in WorkflowArtifactsPerStepComponent](https://trello.com/c/glp8UPmc/2512-fix-issue-in-workflowartifactsperstepcomponent)

**Comment by danidoni** [comment]
Okay, this is what I got.

The trigger here is the `set_flags` step from the provided configuration file.

Before [this change](https://github.com/openSUSE/open-build-service/commit/32aaa8d27bb2e5edb65b09e913e39ea9de23d8d1#diff-31a007d4a9a890ecf1c0b5d981e125576125b3257a6aba21588a1009f1ba7ef5L25) we didn't check if the artifacts were present or not before saving them to the database. This filled the `artifacts` column with the string `"null"`. 

We store the artifacts as a JSON formatted text, and that `"null"` string is not valid JSON, that's why the push event page was failing.

I'm closing this issue as this is not happening anymore and the push event page should work now.
