### ISSUE TITLE
building pam package

### ISSUE THREAD

**Issue by crazyss** [openSUSE/open-build-service#12285]
hello package team,

when I use obs build pam package for fedora system;
it could build done, but it is a base package in build base environment; so i will broken like this：
`
[   95s] [170/470] installing p11-kit-trust-0.23.22-4.fc35

[   96s] [171/470] installing vim-minimal-2:8.2.3404-1.fc35

[   96s] [172/470] installing gawk-5.1.0-4.fc35

[   96s] [173/470] installing pam-1.5.2-25.1

[   96s] 	file /etc/environment from install of pam-1.5.2-25.1.aarch64 conflicts with file from package setup-2.13.9.1-2.fc35.noarch

`
how can I flush this old package? so that I can continue the normal build stage.

**Comment by danidoni** [comment]
Hi @crazyss, I'll close this issue as this is the issue tracker for the OpenBuildService, but it's not the place to ask for help from the packaging team. In order to get help about packaging, you need to send an email to the packaging team's mailing list: 

    packaging@lists.opensuse.org. 

Explain your problem there and someone will surely help you.

**Comment by crazyss** [comment]
Thanks; Got it!
