### ISSUE TITLE
Unexpected notifications for watched projects

### ISSUE THREAD

**Issue by marxin** [openSUSE/open-build-service#13244]
I'm receiving notifications for a `openSUSE:Backports:SLE-15-SP5` project and I don't know why.
Note that #12962 would help me here.

1. examples request: https://build.opensuse.org/request/show/1011366
2. my Watch list:
![Screenshot from 2022-10-20 10-10-59](https://user-images.githubusercontent.com/2658545/196893422-bbd5dfee-f0b0-4ddc-9507-96f527a2006c.png)
3. my notifications settings:
![Screenshot from 2022-10-20 10-12-13](https://user-images.githubusercontent.com/2658545/196893842-7112de6a-bc0f-44dc-b32c-09ba96d84b19.png)
![Screenshot from 2022-10-20 10-12-42](https://user-images.githubusercontent.com/2658545/196893855-b8641c86-9092-4f21-87a5-2ee675a3da25.png)
![Screenshot from 2022-10-20 10-12-42](https://user-images.githubusercontent.com/2658545/196893861-0190eee2-bd8b-4920-9127-8d6ffb7c9a10.png)

**Comment by krauselukas** [comment]
Hey @marxin, do you only receive email notification for that or also web notifications?

**Comment by marxin** [comment]
I received both.

**Comment by hennevogel** [comment]
> Note that https://github.com/openSUSE/open-build-service/issues/12962 would help me here.

Not really as it's more the question of *why* you are a subscriber to the event, not what event this triggered (it was the last comment).

**Comment by marxin** [comment]
> Not really as it's more the question of _why_ you are a subscriber to the event, not what event triggered the notification (it was the last comment).

Sure, basically I would like to see a mapping to the Notifications settings as it contains very many checkboxes :)

**Comment by hennevogel** [comment]
Alright we have something ready in #13319 @marxin please tell us ASAP if this happens again

**Comment by marxin** [comment]
Thanks for implementing the debugging scaffolding.

**Comment by krauselukas** [comment]
We use watched_items to render the watched projects in the watch list. That is what the user sees in the webui. In the event system we check for the watched_projects to calculated which users will receive a notification when they have an event_subscription set for source_watcher and target_watcher. The problem is that users now receive notifications for projects that do not appear in their watch list and cannot influence it.

Here we gather the watchers for an event:
[base.rb](https://github.com/openSUSE/open-build-service/blob/e055e612bb96d4db7639c81dcf069984cb29607d/src/api/app/models/event/base.rb#L245)

Here we fetch the watched projects that are going to be rendered:
[projects_for_watchlist_finder.rb](https://github.com/openSUSE/open-build-service/blob/e055e612bb96d4db7639c81dcf069984cb29607d/src/api/app/queries/projects_for_watchlist_finder.rb#L7)

We need to align those

**Comment by krauselukas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix notifications for `source_watcher` and `target_watcher`](https://trello.com/c/8Codrfjl/2832-fix-notifications-for-sourcewatcher-and-targetwatcher)
