### ISSUE TITLE
`POST /source/<project>/<package>?cmd=diff` doesn't support specifying multiple files to diff

### ISSUE THREAD

**Issue by dmach** [openSUSE/open-build-service#13543]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement `osc diff -r <rev1>:<rev2> [file1] [file2] ...` - related to openSUSE/osc#515
I'm unable to run diff on multiple selected files in a package.

**Describe the solution you'd like**
Pass multiple files to the API, get diff for multiple files back.
Possibilities:
 - allow passing multiple `file` args: `&file=one&file=two&...` (this is prettier and widely used best practice)
 - allow passing multiple files in a single arg: `&file=one|two|...`

**Describe alternatives you've considered**
Send multiple requests, concatenate diffs on the client side.
I find it unnecessary complex, implementation would vary from client to client.

**Comment by eduardoj** [comment]
This is already supported in the backend:
- The `file` parameter is already declared as multiple (`file:filename*`). See: https://github.com/openSUSE/open-build-service/blob/7bda4b816e9d538242690e695d8aafef091f1646/src/backend/bs_srcserver#L7586
- There is already code to parse multiple file values. See: https://github.com/openSUSE/open-build-service/blob/7bda4b816e9d538242690e695d8aafef091f1646/src/backend/bs_srcserver#L3188-L3197

I also did some local testing:
- I created a commit which modified three files, and tested the result with `curl` without file filtering:
```
frontend@491eedeba45a:/obs/src/api> curl -X POST "http://backend:5352/source/home:Admin/package_with_diff?cmd=diff"

++++++ somefile.txt
--- somefile.txt
+++ somefile.txt
@@ -1,1 +1,2 @@
-# This will be replaced
\ No newline at end of file
+# This will be replaced
+# Yes

++++++ somefile2.txt
--- somefile2.txt
+++ somefile2.txt
@@ -1,1 +1,2 @@
-Hey
\ No newline at end of file
+# Hey
+# What

++++++ somefile3.txt
--- somefile3.txt
+++ somefile3.txt
@@ -1,1 +1,2 @@
-# Jorl
\ No newline at end of file
+# Jorl
+# Yes yes
frontend@491eedeba45a:/obs/src/api> 

```
- I could confirm that the backend is capable of filtering by several files:
```
frontend@491eedeba45a:/obs/src/api> curl -X POST "http://backend:5352/source/home:Admin/package_with_diff?cmd=diff&file=somefile2.txt&file=somefile3.txt"

++++++ somefile2.txt
--- somefile2.txt
+++ somefile2.txt
@@ -1,1 +1,2 @@
-Hey
\ No newline at end of file
+# Hey
+# What

++++++ somefile3.txt
--- somefile3.txt
+++ somefile3.txt
@@ -1,1 +1,2 @@
-# Jorl
\ No newline at end of file
+# Jorl
+# Yes yes
frontend@491eedeba45a:/obs/src/api>
```

Somehow, the frontend is only passing one value to the `file` parameter, instead of passing all of them.
