### ISSUE TITLE
[webui] Live build log displays literal &gt;

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#1384]
build.opensuse.org is showing `&gt;` in the Live Build Log view, whereas the logfile download has it as `>`.

For example, today's https://build.opensuse.org/package/live_build_log/Kernel:HEAD/kernel-default/standard/i586 has:

```
[ 4099s] depmod: ERROR: Cycle detected: lnet -&gt; libcfs -&gt; lnet
```

**Comment by bgeuken** [comment]
This also happens on the meta configuration view, eg. here: https://build.opensuse.org/package/meta/devel:libraries:c_c++/libconfuse0

**Comment by bgeuken** [comment]
This most likely comes from the recent changes we made to sanitize user provided input.

**Comment by ChrisBr** [comment]
In meta files this seems still to be a problem but in log files it should work.

**Comment by ChrisBr** [comment]
Ok, the logs are fine, when adding a ``echo "<foobar>"`` to a spec it is displayed correctly.
However, when adding the escaped ``&lt;foobar&gt;`` string, it will display it like this. This is also what happens for the _meta file. For code mirror edit this is fine I think because you need to write it like this to write valid xml. For the live log I think we can also neglect this. For the _meta show / not edit we might want to fix it.

However, I think the initial issue is fixed!
cc @bgeuken

**Comment by bgeuken** [comment]
Alright. Then let's close it

Thanks!
