### ISSUE TITLE
[webui] Maintenance request view lists bugs from deleted files

### ISSUE THREAD

**Issue by saschpe** [openSUSE/open-build-service#141]
Happens for cicount="copy" ghost diffs from the API, should be a regression.

Check: https://build.opensuse.org/request/show/144648

**Comment by eduardoj** [comment]
If I understand this correctly, the issue here was that the deleted files and issues appeared because of using a wrong origin (also named old) project `openSUSE:Maintenance:1164`. It should have been `openSUSE:12.1:Update`, instead.

Using the correct origin (also named old) project has already been fixed.

IMHO, the line `next if issue['state'] == 'deleted'` should not have been added. This is removed in #14835.
