### ISSUE TITLE
CPU Flag SSSE3 is not allowed in _constraints

### ISSUE THREAD

**Issue by ronisbr** [openSUSE/open-build-service#1429]
Hi guys!

I'm trying to build julia in OBS using `MARCH=core2` to improve the performance. However, I was seeing random build failures. It turns out that the problem is because the build machine sometimes does not support SSSE3 CPU Flag.

According to the documentation:

http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.build_job_constraints.html#idm139741986842096

the following in `_constraints` file should work:

```
<constraints>
  <sandbox>kvm</sandbox>
  <hardware>
    <memory>
      <size unit="M">4000</size>
    </memory>
    <cpu>
      <flag>mmx</flag>
      <flag>sse</flag>
      <flag>sse2</flag>
      <flag>sse3</flag>
      <flag>ssse3</flag>
    </cpu>
  </hardware>
</constraints>
```

However, I get the following error:
```
constraints validation error: Extra element hardware in interleave
```
when either sse3 or ssse3 is present. Is there a way to fix this?

**Comment by bgeuken** [comment]
Currently only mmx, sse and sse2 are allowed. I created #1443 which would add sse3 and ssse3 as valid flags. Though I don't have any build instances I could use for testing and don't know that part of the code very well.
But I guess that would do the trick.

So in case you are running your own OBS instance you could try out the patch, if you like. Otherwise we have to wait Adrian or Michael are back
