### ISSUE TITLE
Error message: SSL certificate problem: certificate has expired - SUSE 12.3 @ https://download.opensuse.org/repositories/graphics/openSUSE_12.3/graphics.repo

### ISSUE THREAD

**Issue by eveyv** [openSUSE/open-build-service#14577]
Looking to add repo to zypper for ImageMagick on OPEN SUSE 12.3 and we're getting an expired SSL certificate at https://download.opensuse.org/repositories/graphics/openSUSE_12.3/graphics.repo which prevents access to the page by browsers / curl. 

We are hoping to get this license renewed. I am happy to provide more details or assistance if required.

Thanks.

**Comment by bmwiedemann** [comment]
When you check https://en.wikipedia.org/wiki/OpenSUSE#Version_history, you might notice that 12.3 is EOL since 2015 and that is why the devel repo you link is long gone.

If you use current openSUSE Leap 15.5 or openSUSE Tumbleweed instead, `ImageMagick` is available there.

Also: what "license" are you talking about?

**Comment by eveyv** [comment]
The license is in reference to the expired certificate, so license was not the right word.

**Comment by eveyv** [comment]
Anyway, I am not using Tumbleweed or 15.5 so I am closing out. Thanks.
