### ISSUE TITLE
Why can tokens not be bound to projects only?

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#14827]
While implementing a wrapper around tokens, I was wondering why tokens can either be tied to a project+package or nothing at all, but not to a project. Is there any reason for that?

**Comment by adrianschroeter** [comment]
On Mittwoch, 23. August 2023, 09:56:07 CEST Dan Čermák wrote:
> While implementing a wrapper around tokens, I was wondering why tokens can either be tied to a project+package or nothing at all, but not to a project. Is there any reason for that?

it is just not implemented.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by krauselukas** [comment]
@dcermak  Is this a feature request? :)

**Comment by adrianschroeter** [comment]
On Dienstag, 29. August 2023, 14:25:19 CEST Lukas Krause wrote:
> @dcermak  Is this a feature request? :) 

maybe ... but the design would become ugly, since token can also be used to define
the package to be processed. And then we would need to support a mixture of both modes.

Not really keen on it.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by dcermak** [comment]
> @dcermak Is this a feature request? :)

Not from my side. I have no need for this at the moment

**Comment by krauselukas** [comment]
Alright, then I will close this
