### ISSUE TITLE
Auto detect package sources from package scripts.

### ISSUE THREAD

**Issue by sjp760** [openSUSE/open-build-service#15485]
**Is your feature request related to a problem? Please describe.**
It would be nice for the _service file to automatically update when someone updates the source for their packaging script. It would make it easier to use especially if someone mainly uses the web ui or if they update the source from their phone. I do not mean auto detecting the source repo for updates but when someone edits or changes the source for a package the service file reflects it automatically.  It would make OBS a bit more accessible especially with something like Fedora COPR being able to download the source for a package automatically without any extra file.

**Describe the solution you'd like**
I think a checkbox when creating the project would suffice asking people if they want to turn it on or not.

**Comment by krauselukas** [comment]
Hello @sjp760,
I'm not sure if I understand it correctly. Can you provide an example of what should be achieved? What exactly should be automatically be updated in the `_service` file?

**Comment by krauselukas** [comment]
Which obs-service are you using to download the sources currently? I think this would be an issue that should be raised in the Github repository of the corresponding obs-service (you can find them also in the opensuse org, usually prefixed with `obs-service-...`). The code in this repo doesn't have much influence on the obs-services itself, those are dedicated applications.
But from what I understand you might want to use this https://github.com/openSUSE/obs-service-set_version it would be the other way around then, you would use for example the `tar_scm` or `download_files` to download the sources, and then the `obs-service-set-version` service to set the version based on the sources in your `.spec` file. We do something similar here https://build.opensuse.org/package/view_file/OBS:Server:Unstable/obs-server/_service

In case of further question I would please you to reach out for help on the [opensuse packaging mailing list](https://lists.opensuse.org/archives/list/packaging@lists.opensuse.org/) or in the IRC chat (irc://irc.libera.chat/openSUSE-packaging). Here you find people that might be able to help you with this :)
Since this issue would now be either are supportive question or belongs in one of the obs-service repos, I will close it. Hope my hints can still give a bit of help.
