### ISSUE TITLE
[webui] deleting a package records bogus request and commit message

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/open-build-service#1610]
When deleting a package via the webui the recorded request is rq1 and the commit message is "1".

<pre>
$ osc log -D devel:languages:python3 python3-pyramid_zcml | head -n5
----------------------------------------------------------------------------
r3 | TheBlackCat | 2016-03-04 16:43:46 | ea4b04c6853f95979f3dbd8134b0f86d | 1.0.0 | rq1

1
----------------------------------------------------------------------------
</pre>

**Comment by eduardoj** [comment]
The issue here is that the frontend passes a `commit: nil` key value pair to the backend. The backend interprets this as `1`.

This can be workarounded/fixed from the frontend. I created #13971 for that.

Do we still want the backend to behave this way, or should I create an issue to fix that from the backend side? CC: @openSUSE/obs-backend.
