### ISSUE TITLE
WebUI Maintennace incidents overview page no longer shows incident request status

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#1792]
on the maintenance incident overview page:
https://build.opensuse.org/project/maintenance_incidents/openSUSE:Maintenance

The incident status is no longer shown in the 5th column:

- Yellow flag for a maintenance release request in state "review"
- Green flag for a maintenance release request in state "new"
- Red flag for a maintenance release request in state "decline"

**Comment by bgeuken** [comment]
@adrianschroeter That seems to be caused by the number change. The [code](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/webui/project/_incident_table_entries.html.erb#L42) is fetching request ids, but uses the result as it where numbers not ids: ```BsRequest.where(number: rqs_out)```. And without finding a match there isn't any flag icon.

**Comment by adrianschroeter** [comment]
good spot. Fixed in git and on build.opensuse.org
