### ISSUE TITLE
maintenance patchinfo CVE handling broken

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#1871]
There seems to be a problem saving patchinfos with the correct CVE format.
Probably caused by 980e8afb639187378ed8e1f9001c9845b40ce6c0

We used to use this:
    <issue id="CVE-2016-5353" tracker="cve" />
This format can no longer be used in `_patchinfo`

The following format is accepted by a change from our previous use, breaking some tools.
    <issue id="2016-5358" tracker="cve" />

Entering `CVE-2016-5353` in the web UI is accepted, but saving the patchinfo returns 500.

**Comment by andreasstieger** [comment]
actually, possibly fixed by 980e8afb639187378ed8e1f9001c9845b40ce6c0

**Comment by adrianschroeter** [comment]
Nope, it was actually caused by that, since you requested CVE string validation and you entered the wrong format :)

Try to fix the standard mistake for cve strings now and added hopefully a propper error handling there (also for all the other possible errors).

https://github.com/adrianschroeter/open-build-service/commit/8e1a830f9b02d5b0e2a0f505a288db16337d4d42

**Comment by andreasstieger** [comment]
immediate issue fixed now
