### ISSUE TITLE
webui: wrong request listed in maintenance incident list

### ISSUE THREAD

**Issue by andreasstieger** [openSUSE/open-build-service#1874]
This is probably similar to  #1729: In the [maintenance incidents list](https://build.opensuse.org/project/maintenance_incidents/openSUSE:Maintenance), incidents with a pending incoming request are highlighted with an exclamation mark. The output is as follows:

``` html
<td rowspan="1" class="nowrap">
  <a href="/request/show/422622">
  <img
    title="1 open request"
    class="icons-exclamation"
    alt="1 open request"
    src="/assets[...].gif"
  </a>
</td>
```

For incident [:5206](https://build.opensuse.org/project/show/openSUSE:Maintenance:5206), the linked request is [SR#422622](https://build.opensuse.org/request/show/422622), but there is no such request. The correct request is [SR#400952](https://build.opensuse.org/request/show/).

**Comment by hennevogel** [comment]
@adrianschroeter  another place for s/id/number/ I guess..

**Comment by andreasstieger** [comment]
Is this already fixed by 9672ab3861376b81edc925481f7cda27041d6dc8 on master?

**Comment by bgeuken** [comment]
It's not fixed yet

**Comment by lchiquitto** [comment]
Also happens when we try to unlock a maintenance incident that has an associated release request. The Web Interface shows the error: "Project can't be unlocked: Unlock of maintenance incident SUSE:Maintenance:2691 is not possible, because there is a running release request: 136081".

Guessing:
sed -i 's/maintenance_release_requests.first.id/maintenance_release_requests.first.number/g' src/api/app/models/project.rb

**Comment by bgeuken** [comment]
Should be fixed now
