### ISSUE TITLE
Cannot add repositories? No "Add" button?

### ISSUE THREAD

**Issue by martinrotter** [openSUSE/open-build-service#2052]
Srsly, there is no "Add repositories" button.

![bez nazvu](https://cloud.githubusercontent.com/assets/1255302/17800010/d5b09034-65df-11e6-971e-d34b73d31aa9.png)

WAT

**Comment by adrianschroeter** [comment]
That is a regression. Not sure if it was on purpose, but we should re-shape it to

* Don't make the first repo special (changes get committed atm when the first item got  clicked, but nothing happens when the others get clicked).
* Have only one commit again when multiple repos got added/removed

Yep, IMHO we should bring the add/commit button back ;)

**Comment by martinrotter** [comment]
If repo should be added automatically on-checkbox-toggle, then it does not seem to work. Nothing happens.

**Comment by hennevogel** [comment]
Yes this is a bug tracked in #1986
