### ISSUE TITLE
Allow maintainers to remove comments

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/open-build-service#2357]
Comments sections tend to be used by users as an alternative to "send mail to maintainer". For example, packaging questions or comments about new versions are not uncommon. Unfortunately only owners of these comments or administrators seem to be able to remove them. This allows many years out-of-date comments to persist.

Please allow maintainers of packages and projects to remove these zombie comments.

**Comment by eduardoj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow comment removal to maintainers](https://trello.com/c/d3aWQ8dt/108-allow-comment-removal-to-maintainers)

**Comment by simotek** [comment]
It seems that this is broken, I can only delete my comments here https://build.opensuse.org/package/show/openSUSE:Factory/cmake

**Comment by hennevogel** [comment]
We do not take devel projects into account and you are not maintainer (in the OBS sense) of openSUSE:Factory/cmake.

**Comment by simotek** [comment]
Well can you consider this as a feature request to take the bugowner's in devel projects into account when dealing with comments in devel projects. Because they are the real life actual maintainers of the packages and should be able to tidy up the comments section in the packages devel repo just as much as they can tidy up the package itself or its bugzilla entries. If this new feature request would be better in a new issue, I'm happy to open it for you.

**Comment by hennevogel** [comment]
@coolo what do you peepz think?

**Comment by coolo** [comment]
I find this is going too far.  Everyone can make his project a devel project - which would give him permissions to the target project.
