### ISSUE TITLE
Enhancement: osc request sub-command to only add a comment to a request

### ISSUE THREAD

**Issue by jsmeix** [openSUSE/open-build-service#2408]
I would like that I can only add a comment to a request
(without accepting or declining the request)
using plain 'osc' command line tool.

For example when I have noticed a submitrequest
but I need some longer time to check it, I would like
to inform the submitter that I noticed it but that he
needs to be patient e.g. using something like
<pre>
osc request comment -m 'Please be patient' 12345
</pre>

With such a comment other people who are looking
for pending requests would get the info what is going on
which avoids that they also start to work on it
or have to ask around why things are not moving.

**Comment by marcus-h** [comment]
On 2016-12-01 07:17:39 -0800, Johannes Meixner wrote:
> I would like that I can only add a comment to a request
> (without accepting or declining the request)
> using plain 'osc' command line tool.
> 
The best is to file this in the osc issue tracker:
https://github.com/openSUSE/osc/issues/new

> <pre>
> osc request comment -m 'Please be patient' 12345
> </pre>
> 
Alternatively/Additionally, we could also introduce a new
"osc comment" command, because we have several "commentable"
elements (for instance, projects and packages).

**Comment by jsmeix** [comment]
Re-submitted as
https://github.com/openSUSE/osc/issues/250
