### ISSUE TITLE
Migration failure with real life data

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#2574]
I got the follow migration failure with real life data. While our data may be not correct, the migration should be able handle that. Not sure why the code isn't sufficient on first look.

```
== 20170103132257 ChangeProjectPackageNameToString: migrating =================
-- execute("UPDATE projects SET name = SUBSTR(name, 1, 200)")
   -> 0.1725s
-- execute("UPDATE projects SET name = \"\" WHERE name is null")
   -> 0.0024s
-- execute("UPDATE packages SET name = SUBSTR(name, 1, 200)")
   -> 2.7582s
-- execute("UPDATE packages SET name = \"\" WHERE name is null")
   -> 1.9191s
-- change_column(:projects, :name, :string, {:limit=>200, :null=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Cannot delete rows from table which is parent in a foreign key constraint 'incident_updateinfo_counter_values_ibfk_1' of table 'incident_updateinfo_counter_values': ALTER TABLE `projects` CHANGE `name` `name` varchar(200) NOT NULL
/srv/www/obs/api/db/migrate/20170103132257_change_project_package_name_to_string.rb:7:in `change'
/usr/bin/rake.ruby2.4:22:in `load'
/usr/bin/rake.ruby2.4:22:in `<top (required)>'
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete rows from table which is parent in a foreign key constraint 'incident_updateinfo_counter_values_ibfk_1' of table 'incident_updateinfo_counter_values': ALTER TABLE `projects` CHANGE `name` `name` varchar(200) NOT NULL
/srv/www/obs/api/db/migrate/20170103132257_change_project_package_name_to_string.rb:7:in `change'
/usr/bin/rake.ruby2.4:22:in `load'
/usr/bin/rake.ruby2.4:22:in `<top (required)>'
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
Mysql2::Error: Cannot delete rows from table which is parent in a foreign key constraint 'incident_updateinfo_counter_values_ibfk_1' of table 'incident_updateinfo_counter_values'
/srv/www/obs/api/db/migrate/20170103132257_change_project_package_name_to_string.rb:7:in `change'
/usr/bin/rake.ruby2.4:22:in `load'
/usr/bin/rake.ruby2.4:22:in `<top (required)>'
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

**Comment by adrianschroeter** [comment]
@Ana06 can you have a look?

**Comment by adrianschroeter** [comment]
Important, but not super critical since instance is running also without that migration.

**Comment by hennevogel** [comment]
probably one of the foreign key constraints that only exist on production...

**Comment by Ana06** [comment]
@adrianschroeter 

> @Ana06 can you have a look?

I've just seen that message, sorry 😖

**Comment by Ana06** [comment]
@hennevogel 

> probably one of the foreign key constraints that only exist on production...

No, it is in our structure.sql 😕

**Comment by Ana06** [comment]
`incident_updateinfo_counter_values_ibfk_1` **does** exist in our structure.sql file, and I created a project where this foreign key is present and it doesn't fail, so I was not able to recreate this locally. Also, the name (that is what we are changing) is not used in this foreign key, but the id, so this shouldn't affect. So, the migration is altering a column and complaining about the relation over another column. 

Moreover, if the error was cause because of the data, the error would be different 

Although it shouldn't be any object with a name with more than 200 characters as `execute 'UPDATE projects SET name = SUBSTR(name, 1, 200)'` is executed first, I tried how `change_column` would fail if this happened and the error is different:

```
Mysql2::Error: Data too long for column 'name' at row 1: ALTER TABLE `projects` CHANGE `name` `name` varchar(200) NOT NULL
```

And the same a `null` name, different error:

```
Mysql2::Error: Data truncated for column 'name' at row 1: ALTER TABLE `projects` CHANGE `name` `name` varchar(200) NOT NULL
```


But the error we get say that we are deleting a row, something that we are not doing:

```
Mysql2::Error: Cannot delete rows from table which is parent in a foreign key constraint 'incident_updateinfo_counter_values_ibfk_1' of table 'incident_updateinfo_counter_values': ALTER TABLE `projects` CHANGE `name` `name` varchar(200) NOT NULL
/srv/www/obs/api/db/migrate/20170103132257_change_project_package_name_to_string.rb:7:in `change'
```

So the error is caused by something in the database which our Rails application doesn't know and has to be solved in that specific database.

**Comment by Ana06** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) P2: Check migration error from production](https://trello.com/c/SXo42wsM/296-3-p2-check-migration-error-from-production)

**Comment by srinidhibs** [comment]
One weird observation - although, I don't understand what is going on!

This morning, I installed mysql-workbench and connected to the production database (over SSH). From Workbench, when I tried to alter the table, it ran successfully!! Turns out that the following SQL comand **fails**:

```sql
MariaDB [api_production]> ALTER TABLE `projects`  CHANGE COLUMN `name` `name` VARCHAR(200) NOT NULL;
ERROR 1834 (HY000): Cannot delete rows from table which is parent in a foreign key constraint 'attribs_ibfk_3' of table 'attribs'
```

But the following alter command succeeds:

```sql
MariaDB [api_production]> ALTER TABLE `projects`  CHANGE COLUMN `name` `name` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL;
Query OK, 0 rows affected (0.00 sec)
Records: 0  Duplicates: 0  Warnings: 0

```

I'm still trying to find the significance of `CHARACTER SET 'utf8' COLLATE 'utf8_bin'`, but in the meantime, is there a way I could make Rails migration add these options?
