### ISSUE TITLE
2.8: webui: incorrect download url when api_prefix is used

### ISSUE THREAD

**Issue by matwey** [openSUSE/open-build-service#2948]
Issue/Feature description
====================

Hello,

I am running private obs instance, my ```options.yml``` is the following:

```
frontend_host: mydomain
frontend_port: 443
frontend_protocol: https
api_relative_url_root: /obs
```

Expected result
============
When I open pages at https://mydomain/obs/package/binary/project/package
(```app/views/webui/package/binary.html.erb```)
I see text "Detailed Information About foo.rpm" with wrong url attached to foo.rpm link.

It references to ```https://mydomain/build/project/....``` whereas it expected to be ```https://mydomain/obs/build/project/....```

**Comment by mdeniz** [comment]
Hi @matwey I guess that your use case is not for what this option was created about. This option BTW is "dead" code that we will remove. This option was created when we had two instances of our app that talked to each other... and this is not the case anymore.

If you still having an issue about it just open a new one and we can talk about it.

Many thanks!

This also closes #1921.

**Comment by bgeuken** [comment]
It might be worth to mention this in the release notes, if this option got dropped.

And there are still traces in our code. I would at least cleanup the [options.yml.example](https://github.com/openSUSE/open-build-service/blob/2.8/src/api/config/options.yml.example) to guard users from using this.

**Comment by matwey** [comment]
Do I understand correctly, that non-document root installations aren't supported anymore?

**Comment by mdeniz** [comment]
@bgeuken you were late 😄 

I already was doing what you proposed. I created the PR and now it is mentioned in the release notes for 2.9. After merging the PR for removing the "dead" code in master it will be backported in 2.8 too.

**Comment by mdeniz** [comment]
@matwey maybe I explained myself badly... we are going to remove this options because it was meant for having two different instances of our app in the same domain name that talked to each other. One instance was for the webUI and the other for the API (this one in a subdir). This setup is not anymore as we merged both in one instance.

So, if you want to have your OBS frontend app in a non-document root installation you can set this up as a normal Ruby on Rails app that lives inside a subdir, in the end is just an Ruby on Rails app 😄 .

Probably you already saw this, but here is the info to set the app in a subdir https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/#deploying-an-app-to-a-sub-uri-or-subdirectory

Sorry about the misunderstood, and thanks for pointing us indirectly to the dead code.

**Comment by bgeuken** [comment]
@mdeniz alright;-)

**Comment by matwey** [comment]
@mdeniz Then I cannot understand why did you close #1921 I configured obs-api exactly like recommended by Phusion. Issue there that images and styles are referenced by absolute URLs (and therefore not found), and that has nothing common with Phusion configuration.
