### ISSUE TITLE
[production][package#remove_role] No permission to modify package 'bacula' for user 'bruno_friedmann'

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3428]
package#remove_role threw this 0 times
<pre>
No permission to modify package &#39;BLAH&#39; for user &#39;BLUBB&#39;
</pre>
[https://build.opensuse.org/package/remove_role/Archiving:Backup/bacula](https://build.opensuse.org/package/remove_role/Archiving:Backup/bacula)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/597316c2c50e4b0006334320)

**Comment by hennevogel** [comment]
Why is this exception not catched?

**Comment by mschnitzer** [comment]
So the problem is: A maintainer of a packages/projects can remove user privileges. When they're doing this, they can of course revoke their own Maintainer role and they will still be able (at least UI wise) to revoke/add roles till they reload the page (the checkboxes will only get disabled after reloading the page). So if they remove their own maintainer role and try to edit roles afterward, it raises a 500 error. I'm about to fix this but #3695 needs to be clarified first, because my changes depend on that.

**Comment by hennevogel** [comment]
Does not happen anymore...
