### ISSUE TITLE
IssueTracker connection issue handling

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3593]
All the `IssueTracker` methods assume that networks always work, hosts are always up and API rates are never exceeded. It's very nice to be so positive but the real world doesn't work like that 🤠

We should catch connection issues and handle them.

**Comment by evanrolfe** [comment]
> We should catch connection issues and handle them.
@hennevogel what exactly do you mean by "handle them"?

Also what happens if somebody updates an `IssueTracker` url to the wrong url? If we catch those exceptions then we will never know that the issue tracker is connecting to the wrong url..

I've created this PR to make the exception raised more clear:
https://github.com/openSUSE/open-build-service/pull/3630

I also think this is the cause of the "no implicit conversion from string to integer" error too.

**Comment by evanrolfe** [comment]
@hennevogel I propose we close this issue. If the IssueTracker cannot connect then we should raise an error. Then if an error is raised we can decide if it was simply a blip in the network or if it is something that needs fixing.

**Comment by hennevogel** [comment]
ok
