### ISSUE TITLE
webui project restore fails leaving backend project

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#3631]
Issue description
===============

webui project undelete fails because something creates an empty project meta before running 
the undelete command to the backend which fails as a result.

problem is that this creates a situation where api and backend are out-of-sync so only the admin can repair the situation and the user can't run "osc undelete" anymore. I disabled the restore view therefore on our production instances. (after fixing some projects).

A reproduced situation which got not cleaned up can be found in project home:adrianSuSE:OBS_SLE  , but there is no errbit error.

**Comment by ChrisBr** [comment]
After debugging with @adrianschroeter and @lethliel here are some more information:

1) It seems that the project restore code is fine as it is exactly the same as in the API and exists already since a while.
2) While looking at the logs, it seems that after the project got deleted it was saved again:
```
I, [2017-08-17T15:43:51.810526 #16917]  INFO -- : 20170817T154351 DELETE src-opensuse:5352/source/home:adrianSuSE:OBS_SLE?user=adrianSuSE&comment 200 0.078650439
I, [2017-08-17T15:43:52.162224 #16917]  INFO -- : 20170817T154352 PUT src-opensuse:5352/source/home:adrianSuSE:OBS_SLE/_meta?lowprio=1&user=adrianSuSE 200 0.046626568
```
As you can see, after the ``DELETE`` call is another ``PUT`` call. The question is now, why is there another ``PUT`` and where does it come from. One indicator to find it is the ``lowprio=1`` and that there is no ``comment`` parameter. However, I already tried to reproduce it in the rails console: I opened two terminals and fetched a project in both, in one I destroyed the project and in the other one I called store to put the ``_meta`` again. This worked indeed and saved the ``_meta`` file in the backend. However, I tried then to call ``Project.restore`` to undelete the project. From my understanding, this should fail as the ``_meta`` already exists. However, it worked. 

I'm writing my investigations down here as I will be unavailable till mid of next week so somebody else can pick it up and continue. Have fun :+1: 

cc @hennevogel @mdeniz

**Comment by adrianschroeter** [comment]
My first bet would be that it has something todo with the repositories in the project, because the combination of lowprio=1 and no comment happens in project.rb and repository.rb. I could reconstruct the former repository setup in my reproducer project, but I would need to unbreak the current broken state for this ...

**Comment by mdeniz** [comment]
Superseded by https://github.com/openSUSE/open-build-service/issues/3665 because the cause root is the deletion of projects with a particular setup of repos
