### ISSUE TITLE
[production][] Mysql2::Error: Data too long for column 'event_payload' at row 1: INSERT INTO `notifications` (`t...

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3638]
threw this 2 times
<pre>
Mysql2::Error: Data too long for column &#39;event_payload&#39; at row 1: INSERT INTO `notifications` (`type`, `event_type`, `event_payload`, `subscription_receiver_role`, `created_at`, `updated_at`, `subscriber_type`, `subscriber_id`) VALUES (&#39;Notification::RssFeedItem&#39;, &#39;Event::CommentForProject&#39;, &#39;---\nproject: openSUSE:Factory:Staging:adi:59\ncommenters:\n- 53382\n- 55435\n- 15585\ncommenter: 55435\ncomment_body: |-\n  &lt;!-- RepoChecker state=seen result=failed --&gt;\n\n  ## x86_64\n\n  ### [install check &amp; file conflicts](/package/view_file/openSUSE:Factory:Staging/dashboard/repo_checker)\n\n  &lt;pre&gt;\n  found conflict of python-azure-sdk-2.0.0-3.3.noarch with python2-azure-batch-3.0.0-3.3.noarch:\n    - /usr/lib/python2.7/site-packages/azure/batch/__init__.py\n    - /usr/lib/python2.7/site-packages/azure/batch/__init__.pyc\n    - /usr/lib/python2.7/site-packages/azure/batch/batch_auth.py\n    - /usr/lib/python2.7/site-packages/azure/batch/batch_auth.pyc\n    - /usr/lib/python2.7/site-packages
</pre>

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599644b3fc345100086129f7)

**Comment by hennevogel** [comment]
Same is true for `ProjectLogEntry` then. See https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599644c9fc345100086129fb

**Comment by hennevogel** [comment]
I guess these fields should be MEDIUMTEXT...

**Comment by hennevogel** [comment]
@evanrolfe if you address this please also keep in mind that those fields (or all fields?) should be utf8mb

**Comment by evanrolfe** [comment]
> These fields (and Comment.body) should be MEDIUMTEXT in our database.

Although that would probably prevent this from happening again it is not the root of the problem. The root problem is that we are serialising the event's payload differently in events.payload and notifications.event_payload. This explains why those two columns both have the same exact char length (65535) but only notifications.event_payload gets `Mysql2::Error: Data too long`. (Since the event payload is copied from events to notifications in [SendEventEmails](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/jobs/send_event_emails_job.rb#L32).

In `app/models/event/base.rb` we serialise like this:
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/event/base.rb#L128

While in `app/models/notification.rb` its serialised like this:
https://github.com/openSUSE/open-build-service/blob/master/src/api/app/models/notification.rb#L4

I would also suggest that we stop overriding the methods for the raw attribute (payload and event_payload) so that we can create a notification from an event without having to unserialise and then re-serialise.

Finally, you can see the difference demonstrating when you take a look at the raw payload values in the database:
```
MariaDB [api_development]> select event_payload from notifications;
+----------------------------------------------------------------------------------------------------+
| event_payload                                                                                      |
+----------------------------------------------------------------------------------------------------+
| ---
project: project_1
commenters:
- 8
- 7
commenter: 8
comment_body: Hey @user_1 how are things?
 |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MariaDB [api_development]> select payload from events;
+-------------------------------------------------------------------------------------------------------+
| payload                                                                                               |
+-------------------------------------------------------------------------------------------------------+
| {"project":"project_1","commenters":[8,7],"commenter":8,"comment_body":"Hey @user_1 how are things?"} |
+-------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by hennevogel** [comment]
Using the same serialization method sounds like an excellent idea too

**Comment by jberry-suse** [comment]
Presumably this effects the raw comment max length allowed since it ends up being serialized into a field with the same length and thus has to make space for other data?

**Comment by jberry-suse** [comment]
Related to #3584.

**Comment by evanrolfe** [comment]
> Presumably this effects the raw comment max length allowed since it ends up being serialized into a field with the same length and thus has to make space for other data?

Good point, we need to implement both of the solutions mentioned here:
1. use the same serialisation method for events & notifications payload
2. limit the max length of comment.body

**Comment by hennevogel** [comment]
> limit the max length of comment.body

Why would we do that if we can increase the amount of data we can serialize with MEDIUMTEXT?

**Comment by jberry-suse** [comment]
Since the max length I was provided in the other issue was `65,535 characters` which is the same as `mediumtext` I would assume comment.body is already `mediumtext`. If both the field storing the serialization and the comment body are the same length than clearly the `comment.body` needs to be limited below the length of the field to allow for the extra space used by serialization and the extra data including in a single field.

```
comment.body = mediumtext
event_payload = {other_fields: values, not_just_comment_body: body, comment_body, MEDIUMTEXT}
```

One can see how the `mediumtext` is embedded in another `mediumtext` which creates the restriction. Given that the other fields are not fixed width it likely makes sense to come up with some max space they are allowed to occupy and subtract that from the limit allowed in comment.body.

Perhaps something simple like 1000 characters?

**Comment by jberry-suse** [comment]
```
max(y) = 1000 characters
y = "other stuff" + x
clearly x cannot be 1000 characters long
```

**Comment by hennevogel** [comment]
Your assumption is wrong. 65,535 is text, mediumtext would be 16,777,215 chars :-) See https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html#data-types-storage-reqs-innodb

**Comment by evanrolfe** [comment]
I think @jberry-suse 's point is valid. If we have comment.body as MEDIUMTEXT and events.payload as MEDIUMTEXT, then its still possible that the payload will not fit into the max length of events.payload.

**Comment by jberry-suse** [comment]
The length wasn't the point, and I was provided the number so not really an assumption. If the field type was changed that's cool, but clearly I triggered the mysql errors and I did not use 16 million characters to do it. Just let me know what the effective maximum is after all is said and done. This really isn't rocket science.

Until then I'll be using 60,000 to leave plenty of margin.

**Comment by hennevogel** [comment]
If its to big its too big of course...

**Comment by hennevogel** [comment]
@evanrolfe another field to consider -> #3675

**Comment by evanrolfe** [comment]
@hennevogel yeah I'm working on making the serialisation the same for events, notifications and project_log_entries

**Comment by jberry-suse** [comment]
https://github.com/evanrolfe/open-build-service/blob/a14700a84c2c544bd00ae2437d3d04b9a39fdd36/src/api/app/models/event/base.rb#L278-L294

So this trims the event payload. Does that mean the email notification may be shorter than the comment? Once this is deployed (Thursday?) I'll give it a shot in prod and see that the max works.

**Comment by evanrolfe** [comment]
@jberry-suse the emails are sent using the data in the events table (see [SendEventEmailsJob](https://github.com/opensuse/open-build-service/blob/master/src/api/app/jobs/send_event_emails_job.rb)) so yes if the comment cannot fit into the event payload, then it will be trimmed and hence so will the comment as it appears in the email sent out. 

Also "trim" was the word I was looking for while developing that.. "Shorten" never seemed quite right. I will change that when I get the chance.
