### ISSUE TITLE
[production][package#branch] <status code="400">
  <summary>could not apply patch 'project.diff'</summary>
</status>


### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#3801]
package#branch threw this 1 times
<pre>
&lt;status code=&quot;400&quot;&gt;
  &lt;summary&gt;could not apply patch &#39;project.diff&#39;&lt;/summary&gt;
&lt;/status&gt;

</pre>
[https://build.opensuse.org/package/branch](https://build.opensuse.org/package/branch)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/59b6c4d31d0435000612241c)

**Comment by bgeuken** [comment]
The "old" way of branching allowed to add patches for the actual link. This can result in conflicts when the linked source change.
IMO this is what is happening here `could not apply patch 'project.diff'`.

We probably could catch this and show it in a nicer way. But given that very few packages have such a setup nowadays, I would rather close this.

Please re-open if it turns out that this affects more people.
