### ISSUE TITLE
Changes at repositories in the KIWI Editor don't reflect in the autocompletion of the binaries

### ISSUE THREAD

**Issue by mdeniz** [openSUSE/open-build-service#3958]
Issue/Feature description
====================
At the KIWI Editor, when I change the repositories setup before saving the autocompletion doesn't reflect that changes (at least when removing repositories)

Expected result
============
That the autocompletion works not including repositories that are not there

How to Reproduce
===============
1. Branch an Image Template
2. Write some letters for autocomplete binary packages in the Add package action
3. Remove all the repositories there
4. Retry the autcompletion, it should be empty but is not

**Comment by ChrisBr** [comment]
I'm a little confused now because I wasn't able to reproduce it. And it seems like it is implemented in this commit already
https://github.com/openSUSE/open-build-service/commit/bbe3380276357b3e0c1d64a8bfea62bb21e5e202#diff-cb1030a2a50d2c7fef6a35a0c2bc1f97

(And yes, I tried with adding and removing repositories)

@mdeniz can you please bring some light into the darkness.

**Comment by mdeniz** [comment]
I'm also not able to reproduce it, so let's close it and see if it pops up again. Thanks
