### ISSUE TITLE
Events are sent multiple times to RabbitMQ 

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#4028]
The rabbitMQ sending is bound to after_commit. This happens whenever the event changes.

- INSERT
- UPDATE `events` SET `project_logged` = 1
- UPDATE `events` SET `mails_sent` = 1
- ...

This is arguably a *huge* problem.

**Comment by coolo** [comment]
Small demo: one comment, 3 events - I bet one more is coming later.

```
coolo@f84#rabbit>python /suse/coolo/rabbit/t.py 
 [*] Waiting for logs. To exit press CTRL+C
 [x] 'opensuse.obs.project.comment':'{"project":"home:coolo","commenters":[5],"commenter":5,"comment_body":"test"}'
 [x] 'opensuse.obs.project.comment':'{"project":"home:coolo","commenters":[5],"commenter":5,"comment_body":"test"}'
 [x] 'opensuse.obs.project.comment':'{"project":"home:coolo","commenters":[5],"commenter":5,"comment_body":"test"}'
```

**Comment by coolo** [comment]
And there it is:

```
 [x] 'opensuse.obs.project.comment':'{"project":"home:coolo","commenters":[5],"commenter":5,"comment_body":"test"}'
```

Note that the test instance still has notify_backends code, so *one* of the 4 is gone in master.

**Comment by crazyscientist** [comment]
Hi developers,

I'm afraid to be the bearer of bad news, but this problem is definitely not solved for all event types. A single commit still causes **4** messages to be sent, but with a different topic: `*.obs.project.update`.

Please don't kill the messenger.

**Comment by hennevogel** [comment]
If you see 3 events, then 3 events happened. Probably the way osc commits. @lethliel?

**Comment by adrianschroeter** [comment]
dunno your usecase, but you want to check if a new revision got created and not how many times commitfilelist got called here most likely.

**Comment by crazyscientist** [comment]
> dunno your usecase, but you want to check if a new revision got created and not how many times commitfilelist got called here most likely.

Honestly, I don't know what's happening on the inside. To me the build service is a block box.

I run `osc ci` for a single file and end up with one `commit` message and three `update` messages. I have described the use case in more detail in OBS-74 in Jira.

**Comment by adrianschroeter** [comment]
On Montag, 2. November 2020, 13:58:43 CET Andreas Hasenkopf wrote:
> > dunno your usecase, but you want to check if a new revision got created and not how many times commitfilelist got called here most likely.
> 
> Honestly, I don't know what's happening on the inside. To me the build service is a block box.

it was not really directed to you, more to the component creating the events.

> I run `osc ci` for a single file and end up with one `commit` message and three `update` messages. I have described the use case in more detail in OBS-74 in Jira.



-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by hennevogel** [comment]
> dunno your usecase, but you want to check if a new revision got created and not how many times commitfilelist got called here most likely.

We are not checking anything. We just send out events as they happen on `/lastnotifications`.

@crazyscientist maybe it would help if you could tell us what you want to achieve?

**Comment by crazyscientist** [comment]
> maybe it would help if you could tell us what you want to achieve?

You might be aware of our tool to track and visualize the maintenance process: SMELT. Instead of querying everything that might be interesting (incidents, channels, products, requests; that might be updated files and updated attributes) and might have changed, we use RabbitMQ to update data only once it's changed.

Well, I followed the documentation and subscribed my listener to every topic that sounded interesting. And as it happened, I stumbled across this behavior, where a `osc ci` for a single file caused this cascade of messages:

* suse.obs.package.update
* suse.obs.package.update
* suse.obs.package.commit
* suse.obs.package.update

As I have said, to me the internals of the build service are a black box. I actually understand what the `commit` message is trying to tell me, but the purpose of three additional `update` messages is beyond me. Even if it's an empty package and this is the first commit. To me this looked suspicious and I wanted to tell somebody.
