### ISSUE TITLE
don't know how to create a key

### ISSUE THREAD

**Issue by alexmirtoff** [openSUSE/open-build-service#4152]
Have a nice day. 

When I try to create a project:

```
osc -c ~/.obsadmin_osc.rc -A https://obs meta prj -e ProjectName
Sending meta data...
BuildService API error: 400
don't know how to create a key
Try again? ([y/N]): 
```

What can be wrong? Help me please.

**Comment by lethliel** [comment]
This looks like a private instance. 
I think either sign or the entry in BSConifg.pm is missing. 

`$our $sign = '/usr/bin/sign'`

sign is in the package obs-signd

Please use the mailinglist opensuse-buildservice@opensuse.org or the IRC channel #opensuse-buildservice on Freenode for support questions. 

I am closing this, because this is not an issue of the open build service server. 

If you need further assistance please use irc or the mailing list.
