### ISSUE TITLE
Notifications#event_payload too long

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#4161]
There are over [400 exceptions in errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/599644b3fc345100086129f7) about this. All for the `openSUSE:Factory:Staging` projects.

@jberry-suse looks like some script is passing too much data again. 

I still think this should be medium text as mentioned in #3638

**Comment by coolo** [comment]
this is the repo checker complaining about rubygems having file conflict between 2.4 and 2.5. For comments there should be a limit IMO - but this limit shouldn't be the event_payload, agreed :)

If @jberry-suse saw a '400 too much data in comments' instead of a 500, he would perhaps check his scripts :)

**Comment by jberry-suse** [comment]
So as I asked for in the original issue...what limit do I use? I added comment truncation that handles formatting and what not properly, but need the limit. Last I checked it was working, but as discussed in original thread the implementation was done such that the limit is likely to be inconsistent since it depends on what else ends up in the payload.

https://github.com/openSUSE/osc-plugin-factory/blob/60cdcec090374af8f39002f60210b9ff505f4cdc/osclib/comments.py#L147-L176

I can just drop the limit by several thousand and cross my fingers. My $0.02 I would suggest picking a limit for commits that allows margin for notification mess and validating as such so a proper error is given and I'll use the same limit.

**Comment by coolo** [comment]
Don't you think that 64K of comment is too much - no matter if it ends up in a mail or not?

**Comment by coolo** [comment]
most of the issues exploding now are 'there is some generic problem with 2 sets of packages' - the exact number of files conflicting isn't that interesting.

IMO you're abusing the comment system there - and the build service should restrict comments to a saner level than 64K.

**Comment by hennevogel** [comment]
@jberry-suse it's not about you. my mention was just meant informative :-)

**Comment by jberry-suse** [comment]
Mixed messages. :-) Unless the notification payload is increased I will need to decrease tool limit to one number or another.

As to size of message, the goal was to provide feedback to user from the tool and the tool provides the message. Given that the tool does not provide structured output short of simply truncating the message it is a bit of work to condense it effectively. So as goes the rule the "simplest thing that can work" was done first as the primary goal was submitters actually being able to see the messages directly which was not previously possible and the other goals of the re-write which are not relevant to this discussion.

At this point we could look at parsing the text and condensing or just truncating to a shorter length. Alternatively, having a better place to store the data might be useful, but the comments being used for the purpose has become the norm for these tools, as you know, for lack of any better mechanism. One issue with shortening is that problems may end up being fixed in repeated batches due to not being able to see the full output. In some cases sure it is just a list of files between two packages, but in other large stagings it can be a series or more complex messages that involve multiple submissions. If the message is cut too short not everyone will see the messages effecting their package in the first round (or second, or third...). Obviously, this can still happen with the current max. Since the comments are always removed since stagings are re-used it is not as if these comments are being kept long-term and should only require storage of active set which does not increase over time.

Could additionally, upload the full message to pastebin, but most pastebins have a similar limit. So short of having a proper place to host the full output, or perhaps using one of various storage providers like S3 or somesuch comments are clearly the only real solution at the moment.

**Comment by Ana06** [comment]
This should be done... closing!
