### ISSUE TITLE
openSUSE owners link in CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by ankitkataria** [openSUSE/open-build-service#4442]
Issue description
====================
The link for openSUSE owners(https://github.com/orgs/openSUSE/teams/owners) under the heading "How to conduct yourself when contributing" is broken.

Expected result
============
Should link to maintainers of the OBS, alternatively can also mention reporting the issue in mailing lists or IRC.

**Comment by ankitkataria** [comment]
Can I self-assign the issue?

**Comment by Ana06** [comment]
@ankitkataria what link exactly do you mean? 🤔

**Comment by ankitkataria** [comment]
![image](https://user-images.githubusercontent.com/22021150/35744401-49c21d1a-0866-11e8-9666-31f73db5507a.png)
Sorry, I should've mentioned, its the "openSUSE owners" link in CONTRIBUTING.md

**Comment by mschnitzer** [comment]
It is not possible to see the owners for non-organization members. As an organization member you could use that link: https://github.com/orgs/openSUSE/people?utf8=%E2%9C%93&query=role%3Aowner (just for the record)

**Comment by hennevogel** [comment]
Hm that stinks, sorry. The only viable thing I can think of is pointing to https://en.opensuse.org/openSUSE:Board

**Comment by Ana06** [comment]
@hennevogel 

> Hm that stinks, sorry. The only viable thing I can think of is pointing to https://en.opensuse.org/openSUSE:Board

I agree with @hennevogel :+1: 

@ankitkataria  do you still want to do this? :smile:

**Comment by parasitecruncher** [comment]
@Ana06 Can I do this?

**Comment by Ana06** [comment]
it seems @ankitkataria is not working on it anymore, so @parasitecruncher go ahead! :wink:

**Comment by C-Lion** [comment]
@Ana06 I realize it is getting to be the last minute, but I was waiting for a personal issue to resolve to be sure I can commit to GSoC. It looks like this issue was never fixed. 
Would it be ok for me to fix this issue so I can submit a GSoC proposal to openSUSE?

**Comment by marcus-h** [comment]
On 2018-03-25 01:13:22 +0000, C-Lion wrote:
> Would it be ok for me to fix this issue so I can submit a GSoC proposal to openSUSE? 
> 
Fixing stuff is always appreciated;)
(But even if you don't have a PR just submit your proposal... I'm _sure_
the people love cool and fancy ideas;) )

**Comment by C-Lion** [comment]
@marcus-h I created a pull request but this comment was also added here. Is this normal? 
Is there a better venue to I discuss my GSoC proposal before submitting? Thanks

**Comment by marcus-h** [comment]
On 2018-03-24 20:47:06 -0700, C-Lion wrote:
> @marcus-h I created a pull request but this comment was also added here. Is this normal? 

Yes, because the PR refers to this issue.

> Is there a better venue to I discuss my GSoC proposal before submitting? Thanks
> 
Probably, the best is to get in touch with the mentor(s) directly
(e.g., via email, irc etc.)

**Comment by Ana06** [comment]
@C-Lion 

> @Ana06 I realize it is getting to be the last minute, but I was waiting for a personal issue to resolve to be sure I can commit to GSoC. It looks like this issue was never fixed.
Would it be ok for me to fix this issue so I can submit a GSoC proposal to openSUSE?

Great to know that you plan to send a proposal! :wink: 

As @marcus-h said, you can send the proposal anyway. We recommend to work on something to help you writing a better proposal, but we do not require that you have an accepted PR or anything like that to be able to apply. **It is not a requirement to be selected**.

This issue is just documentation, so it won't help you much for the proposal (it would allow you to know how we revire PR but not to learn how the development environment is set up and the project is structured). Of course you can fix it (as @marcus-h said, fixing stuff is always appreciate), but you can also take something code related and started it, it is not important that it is not finished.

To discuss the proposal, you can contact me or @bgeuken directly.
My email: anamma06@gmail.com and my IRC nick in Freenode: Ana06 (something is Ana006 or other random number of 0s) :stuck_out_tongue_winking_eye: 


And @marcus-h  thanks a lot for replying that fast! :heart_eyes:

**Comment by C-Lion** [comment]
Yes, many thanks to @marcus-h for that fast response. It really makes one feel wanted!

I just posted my draft on the GSoC for the Automate Trollolo usage project and will send the link via email as well. If I don't hear from anyone, I'll just submit it in about 4 hours or so, so I don't accidentally miss the deadline & hope you all like it!

Nice meeting everyone!

**Comment by C-Lion** [comment]
Does openSUSE participate in Outreachy too?

**Comment by Ana06** [comment]
@C-Lion 

> Does openSUSE participate in Outreachy too?

No :no_mouth: Currently GSoC is the only mentoring program in which we are participating (as far as I know at least). :wink:

**Comment by Ana06** [comment]
Fixed in #4729
