### ISSUE TITLE
I shouldn't be able to see everybody's cloud uploads

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4557]
If I click the `All Cloud Uploads` link in the EC2 Uploader page, I can see everybody's uploads. I think that is not expected and I only see my uploads, it any. :confused: I don't know if this is because I didn't add credentials or because I didn't upload any image.

![image](https://user-images.githubusercontent.com/16052290/36547952-5456c922-17ef-11e8-9851-aeee79e59086.png)

![image](https://user-images.githubusercontent.com/16052290/36547978-676310f2-17ef-11e8-925b-910b3101c724.png)

**Comment by ChrisBr** [comment]
> I don't know if this is because I didn't add credentials or because I didn't upload any image.

It is because you don't have an upload.
If the user has upload jobs, we send a request with the ids to the backend
```
/cloudupload?name=42&name=43
```

If there are no upload jobs, we send an "empty" request to the backend, which responds with ... everything.

```
/cloudupload
```

https://github.com/openSUSE/open-build-service/blob/master/src/api/lib/backend/api/cloud.rb#L18

From my POV this is a backend issue, as I would expect if I don't provide the id, I get an empty response. We could also argue to implement a check in the frontend to not send a request at all if there are no user upload jobs. Maybe we should implement both resolutions.

Removing most of the labels as I don't think this is a junior etc issue.

cc @mlschroe
