### ISSUE TITLE
obs-worker package misses obsworker.service file

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#4915]
Issue/Feature description
====================
When installing obs-worker, there is no ```obsworker.service``` file installed. So, trying to start rcobsworker will lead to the following error:
```Failed to start obsworker.service: Unit obsworker.service not found.```
To workaround that, we need to install obs-server on the worker.

Expected result
============
obs-worker installation should be enough.

How to Reproduce
===============
1. install obs-worker
2. Try to start with ```rcobsworker start```
3. You will get: ```Failed to start obsworker.service: Unit obsworker.service not found.```

Further information
===============
* Version: OBS 2.8 from openSUSE repo

**Comment by ggardet** [comment]
```rpm -V obs-worker``` returns nothing.

```/usr/sbin/rcobsworker``` is a symlink to ```/etc/init.d/obsworker```
```/etc/init.d/obsworker start``` returns: 
```
redirecting to systemctl start obsworker.service
Failed to start obsworker.service: Unit obsworker.service not found.
```

**Comment by ggardet** [comment]
Any progress on this topic?

**Comment by ggardet** [comment]
@adrianschroeter any progress ?

**Comment by adrianschroeter** [comment]
again, what is your base distro?

We will convert this to systemd service, but there is not really an excuse that your systemd is not supporting init files.

**Comment by ggardet** [comment]
The distro is is openSUSE Tumbleweed for aarch64 (headless).
IIUC, the problem here, is that the _obsworker.service_ file is missing, not a systemd problem.

**Comment by adrianschroeter** [comment]
On Freitag, 24. August 2018, 17:00:28 CEST wrote ggardet:
> The distro is is openSUSE Tumbleweed for aarch64 (headless).
> IIUC, the problem here, is that the _obsworker.service_ file is missing, not a systemd problem.

there is no obsworker.service file yet and we running fine on openSUSE workers 
just with the init file.

But you should maybe use a tumbleweed build of obs-worker (from OBS:Server:Unstable),
because older distros may have incompatible rpm macros for handling init files.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by adrianschroeter** [comment]
closing because of not supported mix of old obs-worker package for different distribution on tumbleweed.
