### ISSUE TITLE
UI makes not difference between open and closed issues.

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#5798]
Issues listed in the UI don't state which of them are open and which are closed. So it is relative hard to spot the one which still needs to be handled by the maintainer.

Places where we are showing them are for example the user task list:

  https://build.opensuse.org/user/tasks

or request show:

  https://build.opensuse.org/request/show/633519
  (seems to be different code due to the lack of details there)

A simple solution for this would be to

 * make the links of the open ones red colored 
 * prefix the details (which appear on mouse over) with "$STATE: "

**Comment by coolo** [comment]
https://build.opensuse.org/request/show/633519 states Open for bug numbers. CVE numbers do not have any state - they are just tracking the problem, not the solution.

And I don't think that any open issue still needs to be handled by the maintainer - e.g. we leave security bugs open until the issue is resolved in the update channel, not until the maintainer has handled them. So any kind of colour marking is quite counterproductive.

And for /user/tasks - I for one generally ignore the issues listed there as it's 100% unclear when they appear there for me. Right now it lists https://build.opensuse.org/project/show/openSUSE:Maintenance:8256 there twice for me, but I'm neither packager or maintainer nor do I have any relation to the bug reports listed - it's just a mistery. Not sure what red entries would change there, beside ignoring one more thing

**Comment by quatran** [comment]
If you look at the request you have linked, you will see that the two issues we have the state for (boo#1066489) show the state. 

For the other issues we don't simple have the state. So we cannot show it.
