### ISSUE TITLE
[beta] No request link in /project/requests list

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6129]
/project/requests is not bootstrap yet, but it seems to use webui2 in parts - which creates a bad mixture.

![screencapture-build-suse-de-project-requests-suse-maintenance-7868-2018-10-24-08_47_40](https://user-images.githubusercontent.com/1067203/47411658-c915ff00-d769-11e8-9847-5388f4c02e21.png)

If I leave the beta, I get the icon with the link:

![screencapture-build-suse-de-project-requests-suse-maintenance-7868-2018-10-24-08_48_01](https://user-images.githubusercontent.com/1067203/47411663-ce734980-d769-11e8-9fb1-4af83145685b.png)

**Comment by dmarcoux** [comment]
I suspect this might be related to #5723

**Comment by ChrisBr** [comment]
This is caused by https://github.com/openSUSE/open-build-service/pull/5760/files#diff-46ee7aa8bb4da7c62d9c6c99ff398436R15 introduced in https://github.com/openSUSE/open-build-service/pull/5760

@bgeuken I'm wondering why this patch was necessary at all? The project request page is not migrated at the moment?

**Comment by bgeuken** [comment]
The project request tab was migrated to webui2. But we switched this back some weeks ago. And since the request table can be updated / re-rendered via ajax, there were two place we had to update.
I overlooked one of them. Sorry for that.
