### ISSUE TITLE
feature request: provide osc download url

### ISSUE THREAD

**Issue by arunpersaud** [openSUSE/open-build-service#63]
It would be great if OBS would show a url on the overview page (e.g. under "my actions") that I can just copy and paste so that I can create a local clone on my computer, i.e. "create a local clone using 'osc ...'". something similar to what github has. Since I don't use the build server that often I always have to look up how to do this.

**Comment by ChrisBr** [comment]
Please also note that git / github supports a clone on the full URL which osc does not. So I don't think this makes much sense at the moment.

Example:
```
git clone git@github.com:jruby/jruby.git
vs.
osc co home:cbruckmayer/test
```

So with ``osc co`` it will always use ``build.o.o`` or we would need to specify the full command like ``osc -A api.foo.bar co home:cbruckmayer/test`` otherwise it won't work (github for instance only shows the URL and not the full command). So it is not that straight forward. Maybe this is sth we want to support in osc first @lethliel ?

**Comment by bmwiedemann** [comment]
https://build.opensuse.org/package/show/openSUSE:Factory/bash
should then have
```bash
osc -A https://api.opensuse.org checkout openSUSE:Factory bash
```
(because you cannot rely on this OBS being the default in a user's .oscrc)

**Comment by wstephenson** [comment]
Any chance of this making it into the new UI?

**Comment by hellcp** [comment]
The cool thing about git's url implementation is that it allows for wider set of actions with one url, between cloning, setting remotes etc, which posting the full command will never allow for (and osc has multiple actions that require specifying api url, project and package). Maybe before implementing this, we could have osc allow `api/project/package` url  (ie. https://api.opensuse.org/home:hellcp/icon-tool) instead of setting -A flag then? The disturl sound fine, until the hash before the package name.
