### ISSUE TITLE
Updating _meta drops required checks on RepositoryArchitecture

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#6341]
The RepositoryArchitecture model stores required checks for built repositories, but these required checks are dropped if updating _meta. As dropping required checks makes staging projects acceptable if they are not.

And as staging projects update _meta all the time, this is a critical issue for SLE Stagings.

**Comment by coolo** [comment]
Just in case this is unclear: it's about master, not about staging-workflow

**Comment by coolo** [comment]
this also drops/invalidates status_reports I just realized :(

**Comment by adrianschroeter** [comment]
This table is referencing the xml structure so it should not be extended without to adapt the xml.
However, we can't not adapt that easily, since it would break the interconnect for older releases. So it makes anyway sense to move the required checks to a different place (we had discussions about that already some month ago).

**Comment by coolo** [comment]
Yes, we have no plans to store the required checks anywhere but in the project associated. But we still have to store in the database related to the repository_architecture. And if those IDs are volatile, we have a problem - not just with the required checks but also with the status reports.

**Comment by coolo** [comment]
Meaning: if you store the repository_architecture's required checks 'somewhere else' you still will need to make sure the connection stays correct on _meta updates
