### ISSUE TITLE
Can't trigger rebuild as maintainer of a package

### ISSUE THREAD

**Issue by jonsger** [openSUSE/open-build-service#6758]
# Can't trigger rebuild as maintainer of a package

## Expected Result
If I'm the maintainer of a package in a devel repository, I expect that I can retrigger a build of this package.

## How to Reproduce
1. Be maintainer of a package in a devel repository and **NOT** maintainer of the devel repository itself. I'm maintainer of [guile-charting](https://build.opensuse.org/package/show/devel:languages:misc/guile-charting), but not of [devel:languages:misc](https://build.opensuse.org/project/show/devel:languages:misc).
2. Go to https://build.opensuse.org/package/live_build_log/devel:languages:misc/guile-charting/openSUSE_Tumbleweed/x86_64
3. Scroll down to the end.
2. Click on "Trigger rebuild".
4. See error:
```
 Error while triggering rebuild for devel:languages:misc/guile-charting: No permission to modify project 'devel:languages:misc' for user 'jbrielmaier'. 
```

## Further Information
* It's happening on https://build.opensuse.org

P.S: In the meantime I became maintainer of `devel:languages:misc` so the problem is "resolved" for me. But in my view this is still a bug.

**Comment by danidoni** [comment]
I've been looking into this and I'm thinking in implementing the following:
1. Check if we have write access to the package, if true, let the build begin
2. If we don't have write access to the package, check if we have write access to the project, if true, let the build begin
3. If we don't have write access to the project, deny the build.
Would that be ok?

**Comment by adrianschroeter** [comment]
On Dienstag, 26. November 2019, 11:21:35 CET Dani Donisa wrote:
> I've been looking into this and I'm thinking in implementing the following:
> 1. Check if we have write access to the package, if true, let the build begin
> 2. If we don't have write access to the package, check if we have write access to the project, if true, let the build begin
> 3. If we don't have write access to the project, deny the build.
> Would that be ok?

IMHO the package policy for update? should be checked. Don't implement something new,
since triggering rebuild is permission wise not different that to be allowed to
make package modifications.

If the policy is not sufficient we should fix that instead of having a parallel implementation.

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by vpereira** [comment]
We validate it in the `Package.backend_build_command` and when we do a `Backend::Connection.post` we do it on the project level.
