### ISSUE TITLE
drop "show who" for maintainers in request page

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#7086]
![image](https://user-images.githubusercontent.com/16052290/53648081-4a612f00-3c3f-11e9-82e6-7b0b74027e9c.png)

>Show who

Why don't you tell me who already? :eyes: I think for 3 or less we can just show the names there

It would also be nice to have a link to people's profiles and not just the name:

![image](https://user-images.githubusercontent.com/16052290/53648180-8bf1da00-3c3f-11e9-8247-37dd000d3e67.png)

**Comment by dmarcoux** [comment]
I agree and a clickable tooltip would be nice if we have only a few maintainers (maybe 5 or less)

**Comment by SDBowen** [comment]
Hello :wave:

Can I help with this issue?

I played around a bit and came up with the following.

List user name(s) when there are three or less maintainers:

![screenshot from 2019-03-06 18-55-37](https://user-images.githubusercontent.com/22715037/53926989-a7475580-4042-11e9-9a03-4d18d8bde123.png)

And a modal (with links!) when there are 4+ maintainers. Dropped "show who" and made "maintainers" the link to the modal:

![screenshot from 2019-03-06 18-56-22](https://user-images.githubusercontent.com/22715037/53927005-b201ea80-4042-11e9-8b11-95780d223149.png)


For the tooltip, would the expected behavior be that a user can hover over the 'maintainers' link, and quickly view a list of maintainers? From there, the user could click the link to bring up the modal?

**Comment by dmarcoux** [comment]
Hey @SDBowen,

Please open a PR with your changes and we can start reviewing. I see a few minor points where we could improve, but it's already good what you did.
