### ISSUE TITLE
why does project have a staging_workflow_id field?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#7269]
This doesn't seem to be correct to me: https://github.com/openSUSE/open-build-service/blob/master/src/api/db/structure.sql#L965

**Comment by bgeuken** [comment]
Because the staging project model now (or for now) [got moved](https://github.com/openSUSE/open-build-service/pull/7188) to a concern and thus part of the project.
As written in the PR we IMO should find a better approach for such cases. Right now we include 9 mixins / concerns into the project class. Most of them are only needed for some workflows.

**Comment by Ana06** [comment]
It is right
