### ISSUE TITLE
The repository download page is unavailable

### ISSUE THREAD

**Issue by quicktrick** [openSUSE/open-build-service#7281]
Hello!  

The [repository download page](https://download.opensuse.org/repositories/home:/quicktrick:/fail2ban-11/openSUSE_Tumbleweed) for [this project](https://build.opensuse.org/package/show/home:quicktrick:fail2ban-11/fail2ban) is unavailable, though the publish flag is set. I created the project yesterday morning and the repository download page has not been available since then. It says "Resource is no longer available! ... Error 404".

Could you please check it?  Thanks in advance!

**Comment by coolo** [comment]
If you hover the icon next to the repository it says 'repository not yet created'. Our download infrastructure is currently under heavy load, sorry

**Comment by quicktrick** [comment]
@coolo , thank you for your prompt reply!  I just cannot find the icon you mentioned, sorry.

**Comment by coolo** [comment]
In the default webui it's a clock - it's between openSUSE_Tumbleweed and x86_64 on the package page.

**Comment by quicktrick** [comment]
Thanks again, I've found it!

**Comment by coolo** [comment]
and the publisher for home projects has a backlog atm of 2800 repos - and it's going through it by the alphabet. You should have picked a different nick :)

**Comment by coolo** [comment]
So the background story is that 15.0 repositories were wiped and rebuilt due to a brief misconfiguration in 15.0 maintenance - see [mailing list post](https://lists.opensuse.org/opensuse-factory/2019-03/msg00329.html)

This lead to a *huge* backlog on to publish repositories _and_ on a lot of data to fetch for mirrors. The combination slowed down our mirror hub's storage drastically, reducing the capacity to lower the backlog. You can see the scale of the problem here: 

![back-home-pub-queue-7d](https://user-images.githubusercontent.com/1067203/55091510-3fb87f00-50b1-11e9-957d-1c12a193e700.png)

We took some measures to prefer backlog reduction over mirroring and we will monitor the situation.

**Comment by quicktrick** [comment]
@coolo , thank you for your kind attention!
