### ISSUE TITLE
Staging project don't have staging tab

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#7357]
If I come from the [staging workflow](https://build-test.opensuse.org/staging_workflows/1), the [staging project info](https://build-test.opensuse.org/staging_workflows/1/staging_projects/openSUSE:Factory:Staging:A) is a tab in the project and I can switch to other tabs from there. But if I do, the Staging tab is gone and I can't switch back.

**Comment by dmarcoux** [comment]
I believe this issue is resolved on `master`. I went on a staging workflow's page (same route as the one provided in the issue's description) and the `Staging` tab is still present when I'm on other tabs (`Users` for example) of the staging workflow project.

Could you have a look @coolo to confirm this is what you meant/wanted?

**Comment by coolo** [comment]
https://build-test.opensuse.org/staging_workflows/1/staging_projects/openSUSE:Factory:Staging:A has a staging tab, sure. But just click on it and you end in "Staging Projects for openSUSE:Factory:Staging:A" - I expect to stay in the staging workflow of openSUSE:Factory not create a staging workflow for a staging project - if that's even possible.

**Comment by dmarcoux** [comment]
Oh, alright. I get it now. Thank you for the quick reply.

**Comment by fcrozat** [comment]
There is some inconsistency for the "Staging" tab itself:
from https://build.opensuse.org/project/show/openSUSE:Leap:15.2:Staging:A, the staging tab is "opened" (so you expect the staging link to be this page, but in fact, it link to the parent overview page : https://build.opensuse.org/staging_workflows/136). And if you are on https://build.opensuse.org/project/show/openSUSE:Leap:15.2:Staging:A, the "Staging" tab url still link to https://build.opensuse.org/staging_workflows/136 instead of https://build.opensuse.org/project/show/openSUSE:Leap:15.2:Staging:A

**Comment by hennevogel** [comment]
Staging is the term we use for the workflow of the project `openSUSE:Leap:15.2`. `openSUSE:Leap:15.2:Staging:A` is a staging project that is part of this staging. 

But you are right, we will make the tab inactive if you view `openSUSE:Leap:15.2:Staging:D`.
