### ISSUE TITLE
Saving the state of Datatables can mislead users

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#7535]
_Originally posted by @coolo in https://github.com/openSUSE/open-build-service/pull/7427#issuecomment-489443630_

It can lead to strange behaviour - I left the page this morning when I had > 100 requests and now that I'm down to 40, it says there is no data. Took me a moment to realize I'm on page 5 of 4.

![screencapture-build-opensuse-org-user-tasks-2019-05-05-18_49_28](https://user-images.githubusercontent.com/1067203/57197364-b412f780-6f66-11e9-92b6-5e02a6a0ebec.png)

**Comment by bgeuken** [comment]
Hm, that's strange. But I would call this an upstream bug and report it there.

**Comment by dmarcoux** [comment]
This is the same issue: https://datatables.net/forums/discussion/36874. It's apparently fixed (according to the last comment in the thread, which is from August 2016).

Another issue which is similar: https://datatables.net/forums/discussion/comment/143424.

If we cannot get upstream to fix this, we could have a workaround by only storing the number of entries shown by using the [stateSaveParams](https://datatables.net/reference/option/stateSaveParams) callback.

**Comment by krauselukas** [comment]
I worked on the issue, and I would like to give a quick summary about it.
It needs some custom code to prevent the datatable from rendering the
empty page due to the change of the amount of records. Datatables saves the
the lastly visited page in the user session, and restores it at the next visit.
In order to fix this it needs a workaround.

```javascript
// Prevent empty datatable page after records have changed
initComplete: function(settings, json) {
  var rowCurrentPage = table.api().rows({page: 'current'}).count();
  var recordsTotal = table.api().page.info().recordsTotal;
  var searchBoxValue = table.api().search();
  if (rowCurrentPage <= 0 && recordsTotal > 0 && searchBoxValue == '') {
    setTimeout(function() {
      table.api().draw(true);
    }, 10);
  }
},
// Prevent wrong sized columns after redrawing the table
drawCallback: function(settings) {
  table.api().columns.adjust();
}
```

The workaround itself needs some workarounds too. So not a really nice approach.
Instead of just fixing this corner case, the idea was to come up with a more
general solution. Something like a button or link that makes it possible to
clear the state of the datatable. This would make it possible to reset things
like the search box, the ordering, paging etc. with one click.
Datatables saves the state even if the table is still in the "default" state.
So even if the user didn't changed something on the sorting for example, the current
state is saved in his session.
Therefore it would be necessary to compare the saved state of the user with some
default values and if it differs, showing the the button/link to clear it.
This would need custom code with a lot of if/else statements, which runs everytime
the datatable gets drawn.
Just always showing a button to clear the state of the table might be confusing.
Any suggestions/ideas? :)

**Comment by hennevogel** [comment]
> Datatables saves the state even if the table is still in the "default" state.

Hier liegt der Hase im Pfeffer!

Maybe try to talk to the datatables people about it? An initial (even if crude) patch is a nice conversation opener 🤠

**Comment by krauselukas** [comment]
@hennevogel I will try to get in touch with them :+1:
