### ISSUE TITLE
obs 2.10 do not return to package view after saving a file

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#8087]
With obs 2.10 after pressing "Save" on an edited file, the application stays showing the edited file. In the opposite with obs 2.9 after saving a file the application returned to the package view. Now additional steps are required to show the package view again: 
1. Scroll to page top
2. Select the package link on page top

It would be nice to let obs 2.10 also return to the package view after pressing "Save" or if not wished by default to have an additional save button to return to the package view e.g. 'Save and close'.

**Comment by dmarcoux** [comment]
Hey @rhabacker,

This change is intentional in `2.10`. We are not going to implement a `Save and Close` button. The same behavior can be achieved by opening the file editor in a new tab (with `Ctrl+click` on the filename), then saving the changes and closing the tab (`Ctrl+W` in _Firefox_). If somehow the file is quite long (in terms of lines), using the `Home` button takes you back to the top.

For some obscure reason in `2.9` (and probably since a looooong time), the `Save` button redirected to the package view after saving changes in a file editor. It's preventing users from editing a file more than once in a row, which is a valid use case.
