### ISSUE TITLE
`osc ls` does not show access-disabled projects but webui does

### ISSUE THREAD

**Issue by jengelh** [openSUSE/open-build-service#833]
When logged in into the obs webui of a private instance, it is possible to browse a "test" project which has been previously created with `<access><disable/></access> <person userid="jengelh" role="maintainer"/>`. However, the same project won't appear when using `osc ls`.

Now, when the instance config is switched from `<anonymous>on</anonymous>` to off, `osc ls` _will_ show the "test" project.

What I expected to happen: always show "test" in `osc ls` because I have permissions for that prj.
Version: obs-api-2.5.95

**Comment by hennevogel** [comment]
So this isn't a bug in the webui but a bug in osc. Please report it there. https://github.com/openSUSE/osc

**Comment by adrianschroeter** [comment]
it would be an api error then....

**Comment by marcus-h** [comment]
On 2015-01-14 03:40:11 -0800, Adrian Schröter wrote:
> it would be an api error then....
> 
Not necessarily, because osc only sends the credentials, if the api
returned a 401 (except we have valid cookie). I think we should add
an option/config option to osc so that it always sends the credentials.
The question is, what the default should be: always send credentials
or just on 401?

**Comment by jengelh** [comment]
Always send the credentials. Why? Because an unconfigured osc asks for credentials in any case the first time it is used.
