### ISSUE TITLE
Build dependency issue

### ISSUE THREAD

**Issue by mgoppold** [openSUSE/open-build-service#8413]
I try to build gnucash and have a package gwenhywfar-beta which is resoved and a package aqbanking-beta which not. 
In my private obs instance both are resolved.

https://build.opensuse.org/package/show/home:mgoppold:tests/gnucash37 has state

```
nothing provides pkgconfig(aqbanking) = 5.99.30beta
```

and https://build.opensuse.org/package/binary/home:mgoppold:tests/aqbanking-beta/openSUSE_Leap_15.1/x86_64/aqbanking-devel-5.99.30beta-lp151.3.1.x86_64.rpm show as provides:
```
...
pkgconfig(aqbanking) = 5.99.30beta	
...
```

**Comment by coolo** [comment]
This is more a support request than a bug - but I guess leaving it open to improve the documentation is sensible :)

The problem is that you have several aqbanking-devel in this project and only one of them is used for building. Which is it you can query:

```
coolo@cleopatra#~>osc api /build/home:mgoppold:tests/openSUSE_Leap_15.0/x86_64/_repository/aqbanking-devel.rpm?view=fileinfo
<fileinfo filename="aqbanking-devel.rpm">
  <name>aqbanking-devel</name>
  <version>5.8.2</version>
```

I.e. it's not the 5.99 - and it does not provide pkgconfig. If you want OBS to pick the right version you need to make sure they are both available by having different names. e.g. aqbanking-devel and aqbanking-beta-devel

**Comment by mgoppold** [comment]
Thank you for your support, I reorganized it to its own subproject, now. 

And with your hint I found out that it is sufficient to deactivate "Use for build" for the package which should not be used.
