### ISSUE TITLE
Debian armhf-only packages get excluded

### ISSUE THREAD

**Issue by Artox** [openSUSE/open-build-service#845]
Hello everyone,
I am running an OBS instance to build arm packages for debian, ubuntu, opensuse, fedora.

Now I have hit a serious problem with the debian builds:
Packages that say "Architecture: armhf" in the .dsc, will simply get excluded, not ever built.
The standard, namely "Architecture: any" works fine.

**Comment by mlschroe** [comment]
How's your scheduler architecture called? The obs-build package maps "armhf" to the "armv7hl" scheduler architecture, so it'll only get build there.

**Comment by mlschroe** [comment]
(See commit 732c8a7b689beba464094b262f66a3fe53a56670 in obs-build from Sjoerd Simons)

**Comment by Artox** [comment]
It is called armv7l.
I think the name armv7hl was obsoleted years ago, making armv7l to be the new armv7hl, and armv7el the new armv7l

**Comment by mlschroe** [comment]
Well, we're talking about OBS scheduler architectures, so it's hard to tell what's obsolete or not. Anyway, after discussing things with our arm folks, I decided to map armv7l to armhf instead of armel. (Commit 5743516bee59ed482b309ca93d80cfa772765586 in obs-build)

So you need to update obs-build to a version that includes that commit and then force a scheduler cold start, so that all dsc files get parsed again.

**Comment by Artox** [comment]
Thats great, with this change it works properly!
