### ISSUE TITLE
Cannot click on 'finished' state in a project monitor

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#8503]
When you are on a project monitor, you can click on a number of package states: 'building', 'succeeded' and 'failed', but you cannot on 'finished'. 
Whereas it could use the same link as 'building', etc.

**Comment by coolo** [comment]
It's not so easy. when the job is building, the log is fetched from the worker directly - if it's succeeded/failed the log is fetched from the result directory. When it's finished/signing the log file is only in the upload directory and the backend won't read it there (also because it might disappear there any minute)

**Comment by coolo** [comment]
(but don't close the issue before at least some explanation is added)

**Comment by ggardet** [comment]
But you can click on `finished` from the package view. Only the project monitor link is broken.

**Comment by coolo** [comment]
the package view links to the previous build then - which isn't exactly helpful.
