### ISSUE TITLE
No prefilled dialog on clicking "Submit package to ..." 

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/open-build-service#8616]
If I click on "submit package" on a branched project the target project, package and description is already filled with related data. 

If I click on "Submit package to ..." after clicking on 'Has a "link diff"' the target project, package and description is empty. This should be similar to the dialog opened with "Submit package".

**Comment by dmarcoux** [comment]
I double-checked and indeed, the target project, target package and description are empty in the case you explained.

Regarding the description, this is expected since it has to be filled by the submitter. As for the target project and target package, those should be pre-filled since we already know what they are in this context.

**Comment by stoecker** [comment]
You should also add the label "Regression".

**Comment by danidoni** [comment]
Looks like I cannot reproduce it. Can you, please, check if this is still happening?

**Comment by stoecker** [comment]
For me it also works now as expected.

**Comment by dmarcoux** [comment]
Alright, thank you @stoecker for checking again.
