### ISSUE TITLE
Error 403 Forbidden when deleting a project inside my own home branch

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/open-build-service#865]
https://build.opensuse.org/package/remove/home:Mailaender:branches:X11:Pantheon/vala gives me

> 403: Forbidden
> Sorry but you don't have the necessary permissions for this request. We think it's best if you try to start again from the home page.

**Comment by andykimpe** [comment]
the insue 866 seems to come from the same problem https://github.com/openSUSE/open-build-service/issues/866

This bug seems to come from the web interface only until an administrator rule this problem.

I advise you to use osc

osc install link http://openbuildservice.org/download/ or http://software.opensuse.org/package/osc

osc english tutorial https://en.opensuse.org/Build_Service_Tutorial

there with a good chance that this tutorial is available in your language so I suggest you do a search on https://de.opensuse.org

**Comment by coolo** [comment]
indeed
