### ISSUE TITLE
Strange sort order in staging workflow list

### ISSUE THREAD

**Issue by coolo** [openSUSE/open-build-service#8680]
I can't say what the projects in https://build-test.opensuse.org/staging_workflows/1 are sorted after.

creation time? I have B, adi:5, adi:6, ... adi:223, adi:1, adi:3, adi:4, ..., adi:220

The Factory staging dashboard sorts by state, but I guess sorting by name would be acceptable (as it would allow async loading of the state)

**Comment by DimStar77** [comment]
I am an active user of the 'sort by state' - as it gives me a very quick overview of where what kind of work is needed (e.h. pending reviews only, failures, which I need to bring to the attention of maintainers or possibly can solve by merging stagings)

so, if in any way possible, keeping the sorting we currently have, that would be much appreciated

**Comment by fcrozat** [comment]
For SLE, since we don't use adi these days, I'm wondering if we should sort by state (Green on top, Red at the bottom) or just sort alphabetically, since we don't have a lot of stagings anyway.
Both have pro and cons, I'm not sure which one is best.

If sorting by state, it should bring the "actionnable staging" at the top, so, Green THEN Review THEN Red (or somthing like repo-checker or packagelist red), then TEST/Building.

**Comment by gyr** [comment]
I like the current sort by state, for the reason already mentioned in previous comments, it groups the stagings by action that needs to be taken.

**Comment by dmarcoux** [comment]
To answer @coolo's question, the staging projects on the staging workflow page are not sorted. In the end, it is the same as sorting by creation time since we obviously never change the creation time.

**Comment by coolo** [comment]
At least the sorting order is stable atm - so let's call it a feature to give it a proper sorting
