### ISSUE TITLE
Staging dashboard: yellow somehow annoying

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#8788]
![staging](https://user-images.githubusercontent.com/722232/69709651-13507900-10fe-11ea-92f6-165a892ff237.png)

The choice of the yellow color seems to be suboptimal. It's somehow hurting the eye. Maybe a differnt shade of it or using different variants for requests vs staging project status could help

**Comment by coolo** [comment]
In direct comparision the difference against the colour used in obs_factory shows that the warning colour used in bootstrap is most likely *meant* to hurt the eyes:

![screencapture-f102-suse-de-3000-staging-workflows-136-2019-11-29-07_04_45](https://user-images.githubusercontent.com/1067203/69859230-0a91ab80-1294-11ea-9a74-5d93d9115a4c.png)

![screencapture-f102-suse-de-3000-staging-workflows-136-2019-11-29-10_31_14](https://user-images.githubusercontent.com/1067203/69859211-049bca80-1294-11ea-9471-50c50b2feea3.png)

But I guess picking something completely different is the better choice.

**Comment by hellcp** [comment]
Warning in bootstrap is always paired with black and not white, because yellow and white don't mix too well. Doing just that in this case improves it instantly.
![Screenshot from 2019-11-29 10-51-14](https://user-images.githubusercontent.com/30577011/69860290-3150e180-1296-11ea-817f-4c1efd8ebdc3.png)

@coolo's suggestion seems fine too, less orange and more yellow warning would probably look better overall

**Comment by coolo** [comment]
I don't even think it deserves a warning. I'd go for a blue meanwhile - that's also what we use for staging projects stuck in review. But I can't pick a blue that looks good against this very plain green

**Comment by hellcp** [comment]
Maybe it should stay consistent with the projects review state? That's blue as well, seems like a good blue to me ;)
