### ISSUE TITLE
Staging dashboard: URL inconsistent

### ISSUE THREAD

**Issue by lnussel** [openSUSE/open-build-service#8791]
The Leap staging dashboard is at https://build.opensuse.org/staging_workflows/136 which is pretty non-obvious and different than any other URLs OBS.

Judging from the staging tab in a project it looks like a 1:1 relation so a more straight forward  URL would be e.g https://build.opensuse.org/staging_workflows/openSUSE:Leap:15.2

**Comment by fcrozat** [comment]
In addition, there is some inconsistency for the "Staging" tab itself: 
from https://build.opensuse.org/project/show/openSUSE:Leap:15.2:Staging:A, the staging tab is "opened" (so you expect the staging link to be this page, but in fact, it link to the parent overview page : https://build.opensuse.org/staging_workflows/136). And if you are on https://build.opensuse.org/project/show/openSUSE:Leap:15.2:Staging:A, the "Staging" tab url still link to https://build.opensuse.org/staging_workflows/136 instead of https://build.opensuse.org/project/show/openSUSE:Leap:15.2:Staging:A

**Comment by coolo** [comment]
Can you file an extra issue for that? Or reopen https://github.com/openSUSE/open-build-service/issues/7357
