### ISSUE TITLE
Unresolvable details and worker being used for building not shown when logged-in

### ISSUE THREAD

**Issue by ggardet** [openSUSE/open-build-service#9198]
# Issue Description
On a package page, if you set your mouse over:
* `Unresolvable`: it should show you unresolvable details
* `Building`: it should show you the worker being used for building

While it is working properly when not logged-in, it is broken when you are logged-in.

Expected Result
============
It should work in both cases: logged-in or not.

How to Reproduce
===============
1. Go to a package page on OBS
2. Move your mouse over `Unresolvable` or `Building`
Try for both: logged-in or not

Further Information
===============
* Seen on build.opensuse.org

**Comment by saraycp** [comment]
Thanks for your feedback, @ggardet.

First of all, you are perceiving different behaviors before and after log in because your user is under the [Beta Program](https://openbuildservice.org/2018/10/04/the-beta-program/). You can leave the Beta Program at any time, switching it off in your Profile page. But we really encourage you to stay and use the most recent updates and provide us this kind of useful feedback.

Regarding the issue, once you log in (if your user is in Beta Program) now you should click in the question mark icon to see all the texts you are looking for. Why? We are working on improving OBS for small devices so we avoid using tool-tips.

![Screenshot_2020-03-10 system-lock-formula](https://user-images.githubusercontent.com/2581944/76296827-1ccdad80-62b7-11ea-931a-2d5d1a12f19a.png)

Please, let us know what you think about this solution and if you consider something is missing.

You can find more details about the new features in our [blog](https://openbuildservice.org/blog).

**Comment by ggardet** [comment]
Ah ok!
Could we have both? Mouse over pop-up _and_ details when clicking on question mark icon?

**Comment by saraycp** [comment]
Why is mouse over more useful for you? Just trying to understand the use case.
