### ISSUE TITLE
accepted requests get 500 in the webui

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/open-build-service#929]
https://build.suse.de/request/show/57684

was accepted and is shown with osci rq show correctly.

in the webui it is a 500 error page currently

(IBS)

**Comment by hennevogel** [comment]
Duplicate of #912

**Comment by adrianschroeter** [comment]
On Dienstag, 19. Mai 2015, 06:09:16 wrote Marcus Meissner:
> was accepted and is shown with osci rq show correctly.
> 
> in the webui it is a 500 error page currently

The webui is buggy here, but it runs in this error only, because 
there is no acceptinfo data stored.

This should be the case in future when current git master gets deployed

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imend�rffer, Jane Smithard, Dilip Upmanyu, Graham Norton, HRB 21284 (AG N�rnberg) 
Maxfeldstra�e 5                         
90409 N�rnberg 
Germany
