### ISSUE TITLE
Mouse-over current build result does not work

### ISSUE THREAD

**Issue by coogor** [openSUSE/open-build-service#9303]
Beta program: .moving the mouse over a build result 'unresolvable' does not show any longer the packages that cant be resolved

**Comment by eduardoj** [comment]
This information is now shown hovering on the info icon. See https://github.com/openSUSE/open-build-service/pull/9234

Does it work for you this way?

**Comment by coogor** [comment]
It does...although I dont understand where the benefit of the change is....

**Comment by eduardoj** [comment]
That's explained [here](https://github.com/openSUSE/open-build-service/issues/9198#issuecomment-596985453): "[...] Why? We are working on improving OBS for small devices so we avoid using tool-tips. [...]".

I still remember the first time someone pointed me to the info of a build, hovering over the build result. I didn't expect that information to be there. I hope this change also makes more clear where is the information of a build result, both for new and old users of OBS.

Closing, as this issue is fixed hovering over the info icon.
