### ISSUE TITLE
Admin Link for creating new "news" entry went away

### ISSUE THREAD

**Issue by adrianschroeter** [openSUSE/open-build-service#9309]
There is no link anymore on main page for the admin to create a new "news" item.

**Comment by dmarcoux** [comment]
We moved the actions such as creating, editing and deleting in the `Actions` menu for the homepage and the project overview page.

So to create a status message / news, it's now under the `Actions` menu if you joined the beta program.
![create-status-message](https://user-images.githubusercontent.com/1102934/78027114-1a61ef00-735d-11ea-9ccf-b51e7095488c.png)

Otherwise, it's in the same location as before.

This was announced in our [blog post from March 24th](https://openbuildservice.org/2020/03/24/notifications-redesign/).

**Comment by adrianschroeter** [comment]
urgs .. the beta switched on for unknown reason indeed ...

k, I have the link back.

But having a page specific option in the global header is IMHO not the obvious place to look ...

**Comment by dmarcoux** [comment]
We tried this out to group all actions available on a page, so everything which is actionable is easily found. It's still in the beta since we want to gather more feedback on this before moving ahead (or not) with this on other pages.

**Comment by hennevogel** [comment]
This functionality is now in the left hand sidebar.
