### ISSUE TITLE
Project Monitor z-index issue

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#9350]
In beta there is a problem with the z-index of the selectors on the project monitor page. I can't reach the `All` and `None` helpers

## Beta
![Screenshot from 2020-04-08 12-42-58](https://user-images.githubusercontent.com/514785/78775623-cbd4d600-7996-11ea-9c2f-0a8d0d2cd263.png)

## Not-Beta
![Screenshot from 2020-04-08 12-43-20](https://user-images.githubusercontent.com/514785/78775650-d8592e80-7996-11ea-8890-c934fb10bbe5.png)

**Comment by dmarcoux** [comment]
As I wrote in #9400...

The issue is that the navigation is fixed at the top of the page with `.fixed-top` and this class sets a `z-index` of `1030`, which is more than all dropdowns in Bootstrap (they have `1000`). This is documented in the [official docs](https://getbootstrap.com/docs/4.1/layout/overview/#z-index).

So to fix this, we could change the `z-index` of all dropdowns to be more than `1030`, but as the official documentation says:

> We don’t encourage customization of these individual values; should you change one, you likely need to change them all.

I would strongly be against this. In the end, we have this issue because the project monitor page is using dropdowns in a quite questionable way. This page needs to be redesigned and changing the z-index of dropdowns is not going to fix this poor design.

**Comment by hennevogel** [comment]
> we have this issue because the project monitor page is using dropdowns in a quite questionable way

True that.
