### ISSUE TITLE
[production][pulse#show] undefined method `any?' for nil:NilClass

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#9370]
pulse#show threw this 7 times
<pre>
undefined method `any?&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/projects/multimedia:apps/pulse](https://build.opensuse.org/projects/multimedia:apps/pulse)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5e983269b5149400084b50e8)

**Comment by danidoni** [comment]
This happens when the `@commit` instance variable from [here](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/projects/pulse_controller.rb#L31) is nil. And looking at the before_action, this could happen when the action is not triggered via ajax. I don't know how this can happen though. Any ideas?

**Comment by danidoni** [comment]
> This could happen when the `@commit` instance variable from [Webui::Projects::PulseController](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/projects/pulse_controller.rb#L31) is nil. And looking at the before_action, this could happen when the action is not triggered via ajax. I don't know how this can happen though. Any ideas?

Looking at the error in Errbit, I see there is no Browser field... So I tried getting the url with a curl and it raises the same error, so maybe some crawler is the offender.
