### ISSUE TITLE
[production][package#binaries] undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by DavidKang** [openSUSE/open-build-service#9374]
package#binaries threw this 2 times
<pre>
undefined method `name&#39; for nil:NilClass
</pre>
[https://build.opensuse.org/package/binaries/home:wnereiz:matrix/nheko/openSUSE_Leap_15.1](https://build.opensuse.org/package/binaries/home:wnereiz:matrix/nheko/openSUSE_Leap_15.1)"

~[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5e8be97e59f9be000db4d703)~

[See this exception on Errbit](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/5e8be97e59f9be000db4d703)

**Comment by danidoni** [comment]
So, after looking into this, I've found out the following:
- The package the url points to is a link to some other package.
- The linking package's project has no openSUSE_Leap_15.1 repo configured, but the linked package's project does.
- The call to the backend to build the Build Results box is returning the openSUSE_Leap_15.1 repo, but we don't have it locally.

The fix is to check if the repo exists for the linking package and if does not exist, then do not render the link to download the binaries.

**Comment by hennevogel** [comment]
This doesn't have anything to do with the package being a link. This is link only for the sources. Not for the configured repositories of the package you link from.

The reason that the openSUSE_Leap_15.1  repository does not exist anymore in the project is that it got removed by the user.

**Comment by danidoni** [comment]
> The reason that the openSUSE_Leap_15.1 repository does not exist anymore in the project is that it got removed by the user.

Yes, I forgot that part :sweat_smile:

**Comment by danidoni** [comment]
> This doesn't have anything to do with the package being a link. This is link only for the sources. Not for the configured repositories of the package you link from.
> 
> The reason that the openSUSE_Leap_15.1 repository does not exist anymore in the project is that it got removed by the user.

Trying to do a bit of research here, when I remove a repo from a project, the build gets updated and the repo disappear from the build results box... I don't know how you can get into that situation...
