### ISSUE TITLE
database migration still broken

### ISSUE THREAD

**Issue by M0ses** [openSUSE/open-build-service#9779]
Here from the logs:

```
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'api_production.announcements' doesn't exist
/srv/www/obs/api/db/data/20200528135241_dump_announcements_into_status_messages.rb:13:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'api_production.announcements' doesn't exist
/srv/www/obs/api/db/data/20200528135241_dump_announcements_into_status_messages.rb:13:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Table 'api_production.announcements' doesn't exist
/srv/www/obs/api/db/data/20200528135241_dump_announcements_into_status_messages.rb:13:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate:with_data
(See full trace by running task with --trace)
```

obs version (current master):

```
obs-server:/srv/www/obs/api # rpm -q obs-api
obs-api-2.11~alpha.20200617T224243.916617bcb4-lp151.10499.1.noarch
```

This is a follow-up to #9762

**Comment by M0ses** [comment]
Please let me know if you need a VM for testing/debugging

**Comment by hennevogel** [comment]
Again this script of yours is doing something funky that is not supported by rails...

**Comment by M0ses** [comment]
@hennevogel  

* "this script of yours" - this is the script that does the setup of our appliance since I joined the team!
* "rake db:migrate:with_data" should be reentrant as it was since ages (for me at least since 2015)

**Comment by lrupp** [comment]
> Table 'api_production.announcements' doesn't exist

Which script is supposed to create this table?

**Comment by hennevogel** [comment]
The `setup-appliance.sh` script :point_right:  https://github.com/openSUSE/open-build-service/blob/master/dist/setup-appliance.sh#L280

**Comment by hennevogel** [comment]
Sounds like this did not run. The other issues was also in this area. I'm telling you. There is a script problem :smile_cat:

**Comment by M0ses** [comment]
Different VM / same problem:

```
Jun 18 14:25:05 obs-server-vdi setup-appliance.sh[1784]: Initialize OBS api database (first time only)
Jun 18 14:25:05 obs-server-vdi setup-appliance.sh[1784]: Setting ownership of '/srv/obs' obsrun
Jun 18 14:25:05 obs-server-vdi setup-appliance.sh[1784]: Setting up rails environment
Jun 18 14:25:05 obs-server-vdi setup-appliance.sh[1784]: - Doing 'rails db:create'
Jun 18 14:25:09 obs-server-vdi setup-appliance.sh[1784]: - Doing 'rails db:setup'
Jun 18 14:25:48 obs-server-vdi setup-appliance.sh[1784]: - Doing 'rails writeconfiguration'
```

```
[strong_migrations] DANGER: Lock timeout is longer than 10 seconds: 86400
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'api_production.announcements' doesn't exist
/srv/www/obs/api/db/data/20200528135241_dump_announcements_into_status_messages.rb:13:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'api_production.announcements' doesn't exist
/srv/www/obs/api/db/data/20200528135241_dump_announcements_into_status_messages.rb:13:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Mysql2::Error: Table 'api_production.announcements' doesn't exist
/srv/www/obs/api/db/data/20200528135241_dump_announcements_into_status_messages.rb:13:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate:with_data
(See full trace by running task with --trace)
```

**Comment by dmarcoux** [comment]
I could reproduce this locally in the Docker environment by starting from scratch. I dropped the database with `bundle exec rake db:drop`, then set it back up with `bundle exec rake db:create db:setup`. Once this was done, I then ran `bundle exec rake db:migrate:with_data` which caused the error @M0ses wrote about.

So now, why didn't we run into this in the development environment or in the continuous integration?
It's simply because this isn't how the database should be setup. The script is trying to run data migrations for a new database and this is not needed at all, it doesn't make sense. The error points to the `announcements` table which doesn't exist anymore, but the table did exist when the data migration was created and successfully executed for running instances of OBS.

**Comment by dmarcoux** [comment]
In the PR linked above, we ended up only removing the monkey patch on `Rake::Task`. We would have liked to prevent data migrations from doing anything when they are executed on a new database, but there's some quite weird stuff happening in the rake tasks from `data_migrate` (the gem we use for data migrations). We prefer to invest time in other areas of the code.

In the end, the point still stands that running data migrations on a new database doesn't make sense. This is why there are still errors because this is what the script is trying to do. The script needs to be changed.

**Comment by adrianschroeter** [comment]
The setup-appliance.sh script is our official and documented way to create the database on a new installation.

So please either fix the migration or adapt the script that it works again.

**Comment by M0ses** [comment]
Having a db-migration tool which is not reentrant sounds weird to me!

**Comment by hennevogel** [comment]
Not sure what you want to say with this. Anyway, here is how it is:

In [prepare_database_setup](https://github.com/openSUSE/open-build-service/blob/master/dist/setup-appliance.sh#L238), while setting up a new OBS with a fresh database you should never run into this [else](https://github.com/openSUSE/open-build-service/blob/master/dist/setup-appliance.sh#L281) and you should not run `db:migrate:with_data` because migrations and/or data migrations are not supposed to be run on a fresh database. It makes no sense, the script needs changing.

Yes this might have worked before but just by chance. Nothing in ActiveRecord changed in this regard.

**Comment by hennevogel** [comment]
If you want to test if the data migrations are "reentrant", you can run `rake data:schema:load` before running data migration. Which will just do the same thing: Add the latest migration version to the [data_migrations](https://github.com/openSUSE/open-build-service/blob/master/src/api/db/structure.sql#L432) table in your database and do nothing...
