### ISSUE TITLE
Problems with inherited permissions

### ISSUE THREAD

**Issue by afaerber** [openSUSE/open-build-service#995]
As maintainer of devel:ARM:Factory I branched a package devel:ARM:Factory:Contrib:sunxi sunxi-tools. When I wanted to submit it back via Web UI, I got an error "Unable to submit". This was reproducible.

Workaround: Submitting via `osc sr` worked (318789).

Next, I looked up the submit request in the Web UI. It showed the dialog for me to accept it (and optionally to add myself as package maintainer, which I did not choose), but accepting the SR again failed (with a slightly longer error message). Looking at the Users tab, it did not show me as an inherited maintainer for neither package nor project.

Workaround: I was able to add myself as package maintainer via Web UI, then accepting my SR via the Web UI worked.

Expected: Submitting should work independent of permissions in target project. I should be listed on the Users tab of devel:ARM:Factory:Contrib:sunxi project and able to accept submit requests there. And where I am not permitted to accept submit requests, I should not be shown the text box and button to accept one (inconsistency). Generally permissions should behave the same between osc and Web UI.

**Comment by adrianschroeter** [comment]
Submitting should work independent of permissions in target project => yes
I should be listed on the Users tab of devel:ARM:Factory:Contrib:sunxi project  => your job :)
And where I am not permitted to accept submit requests, I should not be shown the text box and button to accept one  => yes

These inconsistency may come from the fact, that you have permimssions, because you are listed in parent project (eg. devel:ARM), but are not listed in sub projects. We do not want to make people maintainers in sub projects automatically, because they would also receive all the traffic notifications. But they have write permissions there indeed without being listed.

**Comment by afaerber** [comment]
Still I would expect the Web UI to show the inherited users, whether there is a checkmark for maintainer or not (for transparency). Similar to how a package shows inherited users from the project.

**Comment by dmarcoux** [comment]
I'm reviewing issues with the `P3` label.

Users with inherited permissions are displayed, here's one example which has some maintainers with inherited permissions: https://build.opensuse.org/package/users/utilities/bat

I'm closing this since I believe this isn't an issue anymore.
