### ISSUE TITLE
OBS automatically capitalizes package names

### ISSUE THREAD

**Issue by brianredbeard** [openSUSE/open-build-service#9970]
# Issue Description
Attempting to build a package on https://builds.opensuse.org with a capitalized name presently fails.  Attempting to do this through the web interface fails with the following message:

![image](https://user-images.githubusercontent.com/57542/88960603-a37c2a80-d258-11ea-84fa-54920db6ef58.png)

Attempting this using the `osc` CLI utility:

`BuildService API error: failed to branch: Package not found: home:adriweb:CEmu/CEmu`                                            

Expected Result
============
I expected to be able to branch the project to make changes to a package.

How to Reproduce
===============
1. Use the repository https://build.opensuse.org/package/show/home:adriweb:CEmu/cemu
2. Click on "Branch Package"
3. Click on "Branch"

**Comment by dcermak** [comment]
Interesting enough, it doesn't occur via interconnect on my local obs test instance (running OBS v2.10.7). I tried branching `openSUSE.org:home:adriweb:CEmu/cemu` and that worked (obs is interconnected as `openSUSE.org`).

**Comment by hennevogel** [comment]
The package includes a `_link` to the package `CEmu` in the same project. That package does not exist. Branching follows links.

Get rid of the link to the in-existent package and you're fine. With great power comes great responsibility :wink:

**Comment by dcermak** [comment]
I think @brianredbeard is not the owner of the `cemu` package... But even if they were, this means that you can simply disable branching of a package by putting a broken `_link` into your package. This is imho pretty bad from a UX perspective, as you as the end user have literally no clue what the issue is and **no way** how to fix this (I mean you cannot even use the usual contribution mechanism to submit the fix…).

Also, why does this package actually still work? The `_link` is broken, shouldn't the package be broken as well?

**Comment by hennevogel** [comment]
This boils down to the philosophical question: Is a branch that links to a package that does not exist still a link or not? Think git detached HEAD. Not sure what the answer is...

> This is imho pretty bad from a UX perspective, as you as the end user have literally no clue what the issue is

Well, the UI error message could tell you a bit more about what is wrong, you are right. See #9971 

> and no way how to fix this

There is a way to fix this. Talk to the maintainer.
